export const ASSISTANT_KNOWLEDGE = [
  {
    id: 'online-publish',
    title: 'Set online stellen (Website verfügbar machen)',
    keywords: ['online', 'website', 'webseite', 'verfügbar', 'set online stellen', 'veröffentlichen', 'publizieren', 'go live', 'live stellen'],
    answer: 'So stellst du ein Set online:\n1) Workspace verbinden und Settings speichern.\n2) Im Tab "Set Import" Audio/Cover/Tracklist laden.\n3) Draft prüfen (id, title, file, tracks).\n4) "Publish nach Settings" nutzen, wenn Auto Deploy aktiv ist, oder "Alles ausführen & Live" für die erzwungene Live-Pipeline.\n5) Erst wenn der Publish Log den Schritt "verify" erfolgreich zeigt, ist das Set wirklich live.\n\nBei Fehlern: Build-/Deploy-Command in Advanced Settings prüfen.',
    actions: ['navigate:import'],
  },
  {
    id: 'workspace',
    title: 'Workspace konfigurieren',
    keywords: ['workspace', 'ordner', 'projekt', 'verbinden', 'pfad', 'root', 'verzeichnis'],
    answer: 'Der Workspace ist das Herzstück des Flight Decks.\n\n1) Öffne den Tab "Flight Deck" oder "Advanced Settings".\n2) Klicke "Workspace auswählen" und navigiere zum AIRDOX-Projektordner.\n3) Speichere die Settings.\n\nEin gültiger Workspace braucht:\n• package.json\n• src/data/musicSets.js\n• wrangler.jsonc\n• .env mit DATABASE_URL',
    actions: ['navigate:flightdeck'],
  },
  {
    id: 'import',
    title: 'Set importieren',
    keywords: ['import', 'set import', 'audio', 'cover', 'tracklist', 'demo import', 'mp3', 'wav', 'dateien', 'laden'],
    answer: 'Set Import — So gehts:\n\n1) Öffne den Tab "Set Import".\n2) Ziehe Audio (MP3/WAV/FLAC), Cover (JPG/PNG) und Tracklist (TXT/CSV) per Drag & Drop in die Drop-Zone.\n3) Alternativ: "Dateien wählen" Button oder "Demo Import" für Testdaten.\n4) Prüfe den Draft: ID, Titel, Datei, Dauer, Tracks.\n5) Starte "Publizieren" oder "Alles ausführen & Live".\n\nDas Tool erkennt automatisch Dauer, Cover und Tracklist aus den Dateien.',
    actions: ['navigate:import'],
  },
  {
    id: 'publish',
    title: 'Publizieren und live stellen',
    keywords: ['publish', 'publizieren', 'live', 'deploy', 'build', 'go live', 'pipeline', 'alles ausführen'],
    answer: 'Publish vs. Go Live:\n\n• "Publish nach Settings" → Nutzt deine gespeicherten Flight-Deck-Settings. Wenn Auto Deploy aktiv ist, läuft Upload → Manifest → Build → Deploy → Verify.\n• "Alles ausführen & Live" → Erzwingt die Live-Pipeline auch dann, wenn Auto Build/Deploy in den Settings aus waren.\n\nPipeline-Schritte:\n1) Preflight: Workspace + Manifest validieren\n2) Upload: Audio nach R2 hochladen\n3) Manifest: musicSets.js aktualisieren\n4) Build: Frontend neu bauen\n5) Deploy: Via Wrangler/Cloudflare deployen\n6) Verify: Live-Bundle auf der Website gegen Set-ID und Track-Tokens prüfen\n7) Git: Commit + Push (wenn aktiviert)\n\nBei Fehler: Prüfe Build-/Deploy-Command in Advanced Settings.',
    actions: ['navigate:import'],
  },
  {
    id: 'analytics',
    title: 'Analytics und Filter',
    keywords: ['analytics', 'filter', 'zeitraum', 'event', 'gerät', 'land', 'statistik', 'plays', 'views', 'likes', 'engagement'],
    answer: 'Analytics im Detail:\n\nFilter-Optionen:\n• Zeitraum: Von/Bis Datumsfilter\n• Event-Typ: play, like, dislike, view\n• Gerät: desktop, mobile, tablet\n• Land: DE, AT, CH, US, etc.\n\nKennzahlen:\n• Gesamtaufrufe, Plays, Likes\n• Engagement Rate (Plays/Views)\n• Top Sets nach Plays\n• Geo-Verteilung nach Land\n• Tageszeit-Verteilung (24h Sparkline)\n• Geräte-Breakdown\n\nTipp: Klicke "Aktualisieren" um Live-Daten vom Server zu laden.',
    actions: ['navigate:analytics'],
  },
  {
    id: 'db-error',
    title: 'Datenbankfehler',
    keywords: ['datenbank', 'datenbankfehler', 'neon', 'fetch failed', 'db', 'error', 'database', 'connection', 'postgres', 'sql error'],
    answer: 'Datenbankfehler beheben:\n\n1) Prüfe .env im Workspace:\n   • DATABASE_URL oder NEON_DATABASE_URL muss gesetzt sein\n   • Format: postgres://user:pass@host/db?sslmode=require\n\n2) Netzwerk prüfen:\n   • Neon-DB braucht Internetzugang\n   • Firewalls/VPN können blockieren\n\n3) Neon-Dashboard prüfen:\n   • Ist die DB aktiv? (auto-suspend nach Inaktivität)\n   • Sind Credentials noch gültig?\n\n4) Workaround: Das Flight Deck läuft auch ohne DB weiter — nur Analytics/Users/Sessions sind dann nicht verfügbar.',
  },
  {
    id: 'explorer',
    title: 'Data Explorer',
    keywords: ['data explorer', 'sql', 'query', 'readonly', 'table', 'track_stats', 'tabelle', 'daten', 'export'],
    answer: 'Data Explorer — Datenbank direkt abfragen:\n\nTabellen:\n• track_stats: Plays, Likes, Dislikes pro Set\n• analytics_logs: Alle Events mit Geo/Device\n• users: VIP-User Verwaltung\n• sessions: Aktive Login-Sessions\n• subscribers: Newsletter-Abonnenten\n• bookings: Booking-Anfragen\n\nFunktionen:\n• Tabelle wählen → Daten laden\n• Suche: Freitext-Filter über alle Spalten\n• Export: CSV oder JSON\n• SQL: Read-only Queries (SELECT/WITH/EXPLAIN)\n• Inline-Edit: track_stats und subscribers direkt bearbeiten\n• VIP-Admin: User anlegen, Passwort reset, Session revoke',
    actions: ['navigate:explorer'],
  },
  {
    id: 'monitor',
    title: 'System Monitor',
    keywords: ['monitor', 'system', 'cpu', 'ram', 'cache', 'optimize', 'speicher', 'prozesse', 'performance'],
    answer: 'System Monitor — Diagnose:\n\nÜberwachte Metriken:\n• RAM: Belegung in MB und Prozent\n• CPU: Auslastung und Cores\n• Disk: Freier Speicherplatz\n• Prozesse: Aktive Prozesse mit Memory\n\nAktionen:\n• "Cache löschen" → Temporäre Dateien bereinigen\n• "Optimieren" → System-Optimierung anstoßen\n• "Aktualisieren" → Neue Messwerte laden\n\nFarb-Kodierung:\n• Grün: < 70% — Gesund\n• Gelb: 70-90% — Warnung\n• Rot: > 90% — Kritisch',
    actions: ['navigate:monitor'],
  },
  {
    id: 'batch',
    title: 'Batch Import',
    keywords: ['batch', 'mehrere', 'queue', 'masse', 'multiple', 'bulk', 'stapel', 'drag drop'],
    answer: 'Batch Import — Mehrere Sets gleichzeitig:\n\n1) Dateien per Drag & Drop in die Batch-Zone ziehen\n   (oder "Dateien wählen" Button)\n2) Das Tool gruppiert automatisch: Audio + Cover + Tracklist\n3) Queue prüfen: Checkbox = im Live-Run enthalten\n4) "Start" → Drafts vorbereiten (ohne Upload)\n5) "Auswahl live stellen" → Volle Pipeline für alle gewählten Sets\n\nTipps:\n• Gleichnamige Dateien werden automatisch gruppiert\n  (z.B. set1.mp3 + set1.jpg + set1.tracks.txt)\n• Fehler einzeln retrien möglich\n• "Fertige löschen" räumt erfolgreiche Items auf',
    actions: ['navigate:batch'],
  },
  {
    id: 'design-agent',
    title: 'Design Assistant / Design Agent',
    keywords: [
      'design',
      'designer',
      'design assistent',
      'design assistant',
      'design agent',
      'creative lab',
      'creative studio',
      'studio',
      'photoshop',
      'handoff',
      'reel',
      'story',
      'visual',
      'grafik',
      'cover',
      'mp4',
      'gif',
    ],
    answer: 'Schnellster Weg im Design Assistant:\n\n1) Öffne links "Design Agent". Wenn sich das separate Design Studio öffnet, bleib dort nur für das Visual. Zurück kommst du oben über "Hauptansicht".\n2) Wähle zuerst das Musik-Set. Nimm danach genau ein Format: Square für Cover/Post, Reel für 9:16 Video, Story für Hook-Frame.\n3) Wähle ein Look-Preset. Starte nicht mit allen Reglern. Für schnelle Ergebnisse: "Signal System" oder "Club Still Parallax".\n4) Klicke erst dann "Studio" bzw. gehe zur Phase "Feintuning & Marke". Dort nur die drei wichtigsten Regler anfassen: Motion, Glitch, Waveform.\n5) Prüfe Markentext und Hintergrund. Wenn kein eigener Hintergrund nötig ist, Cover/Set-Standard lassen.\n6) Render starten. Danach im Export nur den benötigten Output öffnen: MP4 für Reel/Story, GIF für Preview, Handoff/Manifest nur wenn du weiterbearbeitest.\n\nNicht schneller ist: alle Presets anklicken, jeden Regler ändern und dann ohne klares Format rendern. Das erzeugt nur Variantenchaos.\n\nWenn du nur schnell ein brauchbares Visual brauchst: Set wählen -> Reel -> Signal System -> Studio -> Motion mittel, Glitch niedrig -> Render.',
    actions: ['navigate:design'],
  },
  {
    id: 'flightdeck-map',
    title: 'Flight Deck Tab-Landkarte',
    keywords: ['tabs', 'bereiche', 'übersicht tabs', 'wo finde ich', 'was gibt es', 'navigation', 'landkarte', 'aufbau', 'module'],
    answer: 'Flight Deck Landkarte:\n\nBetrieb:\n• Overview: Systemlage, Snapshot, Git, Manifest, Top Sets, Recent Analytics\n• Flight Deck: Workspace, Pipeline-Grundlagen, Publish-Automation\n\nPublish:\n• Set Import: einzelnes Set vorbereiten und publizieren\n• Batch Import: mehrere Sets als Queue vorbereiten und live stellen\n• Marketing Manager: Manni-Entwürfe, Freigaben und externe Aktionen trennen\n• Design Agent: Visuals, Reels, Photoshop-Handoff und Transfer Packs\n\nDaten:\n• Analytics: Plays, Views, Länder, Geräte, Engagement, Top Sets\n• Data Explorer: Tabellen, Exporte, VIP-User, Sessions, Read-only SQL\n\nSystem:\n• Advanced Settings: Pfade, Build/Deploy, Git, Live Updates, Toggles\n• System Monitor: CPU/RAM/Disk/Prozesse, Cache, lokale Last\n• Tutorial: geführte Szenarien und Checklisten\n• AI Assistant: Fragen stellen, Status lesen und Tabs öffnen',
  },
  {
    id: 'go-live-preflight',
    title: 'Go-Live Preflight Checkliste',
    keywords: ['preflight', 'vor go live', 'vor live', 'checkliste', 'prüfen', 'go live prüfen', 'release prüfen', 'live check'],
    answer: 'Go-Live Preflight:\n\n1) Overview prüfen:\n• Workspace verbunden\n• richtiger Branch\n• Dirty-Status verstanden\n• Manifest/Stats plausibel\n\n2) Settings prüfen:\n• Safe Mode an, wenn Audio lokal vorliegen muss\n• R2 Prefix korrekt\n• Build Command und Deploy Command korrekt\n• Auto Deploy/Commit/Push bewusst gesetzt\n\n3) Draft prüfen:\n• id eindeutig\n• title/date/duration/file korrekt\n• Audio-Quelle vorhanden\n• Cover und Vinyl Color passend\n• Tracklist lesbar und vollständig\n\n4) Pipeline prüfen:\n• Upload nach R2 erfolgreich\n• Manifest aktualisiert\n• Build erfolgreich\n• Deploy erfolgreich\n• Verify bestätigt Set-ID und Track-Tokens live\n\n5) Nachkontrolle:\n• Website im Browser prüfen\n• Overview refreshen\n• Data Explorer track_stats prüfen\n• Publish Log sichern, wenn ein Fehler auftrat',
    actions: ['navigate:overview'],
  },
  {
    id: 'glossary',
    title: 'Flight Deck Glossar',
    keywords: ['begriff', 'begriffe', 'glossar', 'was bedeutet', 'erkläre begriff', 'definition', 'manifest', 'snapshot', 'draft', 'safe mode', 'r2 prefix', 'verify', 'track_stats', 'analytics_logs'],
    answer: 'Wichtige Begriffe:\n\n• Workspace: lokaler AIRDOX-Projektordner, in dem package.json, wrangler.jsonc und src/data/musicSets.js liegen.\n• Manifest: Set-Liste der Website, technisch src/data/musicSets.js.\n• Draft: vorbereiteter Set-Entwurf vor dem Schreiben ins Manifest.\n• Publish: Draft wird ins Manifest übernommen und optional Folgeaktionen gestartet.\n• Go Live: volle Live-Kette mit Upload, Manifest, Build, Deploy und Verify.\n• Verify: Kontrolle, ob das neue Set wirklich im Live-Bundle/auf der Website gefunden wird.\n• R2: Cloudflare Object Storage für Audio-Dateien.\n• R2 Prefix: Zielpfad/Namespace im Bucket.\n• Safe Mode: Schutz, der Publishes ohne echte Audio-Quelle blockiert.\n• track_stats: Tabelle für Plays, Likes, Dislikes und last_played_at je Set.\n• analytics_logs: Event-Tabelle mit play/view/like/dislike, Land, Gerät, Browser und Zeit.\n• Snapshot: aktueller zusammengefasster Zustand aus Manifest, Datenbank und Git.\n• Dirty Git: es gibt uncommittete Änderungen im Repository.\n• Transfer Pack: Design-Agent-Ausgabe mit MP4/GIF/Manifest/Handoff und optional Photoshop-Dateien.',
  },
  {
    id: 'data-model',
    title: 'Datenmodell und Tabellen',
    keywords: ['datenmodell', 'tabellen', 'tables', 'welche tabellen', 'track_stats', 'analytics_logs', 'bookings', 'subscribers', 'users', 'sessions', 'datenbank schema'],
    answer: 'Wichtige Tabellen im Data Explorer:\n\n• track_stats: id, plays, likes, dislikes, last_played_at. Bearbeitbar für Set-Statistiken.\n• analytics_logs: event_type, item_id, session_id, country, city, region, device_type, browser, os, referrer, created_at. Nicht direkt editieren.\n• bookings: Booking-Anfragen mit name, email, event, message, created_at.\n• subscribers: Newsletter-Adressen mit email, status, created_at. Inline bearbeitbar.\n• users: VIP-User mit username, email, created_at.\n• sessions: aktive/alte Sessions mit user_id, username, email, created_at, expires_at.\n\nRead-only SQL erlaubt nur SELECT, WITH und EXPLAIN. Schreibende Statements sind blockiert.',
    actions: ['navigate:explorer'],
  },
  {
    id: 'analytics-terms',
    title: 'Analytics Begriffe und Auswertung',
    keywords: ['views', 'plays', 'likes', 'dislikes', 'engagement', 'conversion', 'event type', 'event typ', 'device', 'geo', 'country', 'hourly', 'tageszeit', 'schwache sets'],
    answer: 'Analytics lesen:\n\n• view: Sichtkontakt oder Seiten-/Set-Ansicht.\n• play: echte Wiedergabe, wichtiger als view für Nutzung.\n• like/dislike: explizite Resonanz.\n• Engagement Rate: Verhältnis von Plays zu Views. Nur mit genug Volumen interpretieren.\n• Top Sets: Ranking nach Nutzung/Plays im gewählten Filter.\n• Geo-Verteilung: Länder-Signal, z.B. DE/AT/CH/US.\n• Device Breakdown: desktop/mobile/tablet; wichtig für UI- oder Mobilprobleme.\n• Tageszeit-Verteilung: wann Nutzung stattfindet.\n\nSchwache Sets analysieren:\n1) Zeitraum sauber setzen.\n2) Erst view vs play vergleichen.\n3) Dann mobile/desktop und Land prüfen.\n4) In Data Explorer analytics_logs kontrollieren.\n5) Bei vielen Views und wenigen Plays: Hook, Cover, Titel, Player oder Ladeverhalten prüfen.',
    actions: ['navigate:analytics'],
  },
  {
    id: 'publish-pipeline',
    title: 'Publish Pipeline und Logs',
    keywords: ['pipeline', 'publish log', 'logs', 'upload', 'manifest', 'build', 'deploy', 'verify', 'commit', 'push', 'live pipeline', 'alles ausführen'],
    answer: 'Publish Pipeline:\n\n1) Preflight: Workspace, Settings, Draft und Manifest prüfen.\n2) Upload: Audio nach Cloudflare R2 hochladen, wenn aktiviert.\n3) Manifest: src/data/musicSets.js aktualisieren.\n4) Stats Seed: fehlende track_stats-Zeile anlegen, wenn aktiviert.\n5) Build: Vite-Frontend bauen.\n6) Deploy: Wrangler/Cloudflare deployen.\n7) Verify: Live-Ausgabe gegen Set-ID und Track-Tokens prüfen.\n8) Git: optional Commit und Push.\n\nWenn der Publish Log fehlschlägt, ist der Schrittname entscheidend. Ein Upload-Fehler ist meist R2/Credentials, ein Build-Fehler Code/Dependencies, ein Deploy-Fehler Cloudflare/Auth, ein Verify-Fehler Live-Bundle oder falsche Set-Daten.',
    actions: ['navigate:import'],
  },
  {
    id: 'settings-toggles',
    title: 'Settings Toggles erklären',
    keywords: ['toggles', 'automation toggles', 'auto deploy', 'auto build', 'auto commit', 'auto push', 'extract embedded cover', 'auto seed stats', 'upload audio', 'settings erklären'],
    answer: 'Wichtige Toggles:\n\n• Safe Mode: blockiert riskante Publishes ohne echte Audio-Quelle.\n• Upload Audio to R2: lädt Audio in Cloudflare R2 hoch.\n• Extract Embedded Cover: versucht Cover aus Audiodateien zu extrahieren.\n• Auto Seed Stats: legt fehlende track_stats-Einträge automatisch an.\n• Auto Build: führt nach Publish den Build Command aus.\n• Auto Deploy: deployt nach Build über den Deploy Command.\n• Auto Commit: erstellt nach erfolgreichem Lauf einen Git-Commit.\n• Auto Push: pusht den Commit auf Remote.\n\nRegel: Je mehr Automation aktiv ist, desto sauberer müssen Workspace, Branch, Audio, R2 und Commands vorher geprüft sein.',
    actions: ['navigate:settings'],
  },
  {
    id: 'agent-system',
    title: 'Agenten, Reports und Projektwissen',
    keywords: ['agenten', 'agents', 'manni', 'designer', 'winnie', 'guardian', 'mentor', 'webbie', 'repository', 'refactor', 'reports', 'latest', 'visual templates', 'projektwissen', 'wiki sync'],
    answer: 'AIRDOX Agentenwissen:\n\n• docs/agent-system/reports/: dauerhafte Reports, Runbooks, Kampagnen, Mentor- und Research-Dokumente.\n• docs/agent-system/visual-templates/: Designer-Ausgaben, visuelle Vorlagen, Contact-Sheets und Social-Assets.\n• docs/agent-system/latest-*.md/json: aktuelle maschinelle Snapshots von Audit, Routing, Health, Jobs, Risiko, Portfolio usw.\n• DECISION_LOG.md: zentrale Entscheidungen.\n\nRollen grob:\n• Webbie: Website/UX/Performance\n• Winnie: Windows Flight Deck/Electron/Automation\n• Guardian: Qualität, Tests, Security, Risiken\n• Manni: Marketing, Reichweite, Social, EPK\n• Designer: Visuals, Creative Direction, Assets\n• Mentor: Lernen, Wiki, Scorecards\n• Repository: Git/GitHub/Release-Hygiene\n• Refactor: Vereinfachung und Architekturqualität\n\nAlte Pfade wie docs/agent-system/social-auto-output/ oder docs/agent-system/research/ sind nicht mehr aktuelle Quellen.',
  },
  {
    id: 'marketing-manager',
    title: 'Marketing Manager / Manni',
    keywords: ['marketing', 'marketing manager', 'manni', 'freigabe', 'approval', 'kampagne', 'social', 'reel freigeben', 'draft request', 'entwurf'],
    answer: 'Marketing Manager:\n\nDer Marketing Manager trennt Entwurf, Freigabe und externe Aktion.\n\nEr kann:\n• Manni-Kampagnen und Operations anzeigen\n• Freigaben für konkrete Social-/PR-Aktionen verwalten\n• Draft Requests mit Ziel, Kanälen und Einschränkungen anlegen\n• Status wie pending/approved/rejected nachvollziehen\n• Assets, Copy und Messfenster sichtbar machen\n\nWichtig: Externe Live-Aktionen sollen nur mit klarer Nutzerfreigabe passieren. Keine andere Copy, kein anderes Asset und kein Paid Spend ohne explizite Freigabe.',
    actions: ['navigate:marketing'],
  },
  {
    id: 'tutorial-workflows',
    title: 'Tutorial und Workflows',
    keywords: ['tutorial', 'tour', 'workflow', 'checklist', 'checkliste', 'szenario', 'lernen', 'geführte tour', 'full tour', 'quick start'],
    answer: 'Tutorial-System:\n\nDas Tutorial ist workflow-orientiert. Es erklärt nicht nur Buttons, sondern führt durch typische Aufgaben.\n\nGrundprinzipien:\n• Erst Zustand, dann Aktion: mit Overview starten.\n• Filter vor Interpretation: Analytics/Data Explorer zuerst eingrenzen.\n• Kleine Zielmengen statt hektischer Massenarbeit.\n• Publish endet erst nach Log, Overview und ggf. Data-Explorer-Kontrolle.\n\nNutze es für:\n• Quick Start\n• Go-Live-Vorbereitung\n• Analytics-Auswertung\n• Data-Explorer-Pflege\n• System- und Settings-Verständnis',
    actions: ['navigate:tutorial'],
  },
  {
    id: 'settings',
    title: 'Advanced Settings',
    keywords: ['settings', 'einstellungen', 'konfiguration', 'safe mode', 'r2', 'build command', 'deploy command'],
    answer: 'Advanced Settings — Alle Konfigurationen:\n\nWorkspace:\n• Workspace Root: Projektordner-Pfad\n• R2 Prefix: Cloudflare R2 Bucket-Pfad\n• Cover Output Dir: Zielordner für Cover-Bilder\n• Build/Deploy Commands: Shell-Befehle\n\nAutomation Toggles:\n• Safe Mode: Blockiert riskante Publishes\n• Upload Audio to R2: Automatischer R2-Upload\n• Extract Embedded Cover: Cover aus Audio extrahieren\n• Auto Seed Stats: Track-Stats automatisch anlegen\n• Auto Build/Deploy: Pipeline-Automatisierung\n• Auto Commit/Push: Git-Automatisierung',
    actions: ['navigate:settings'],
  },
  {
    id: 'tutorial',
    title: 'Tutorial und Hilfe',
    keywords: ['tutorial', 'hilfe', 'help', 'anleitung', 'guide', 'tour', 'lernen', 'einführung'],
    answer: 'Tutorial-System:\n\n• "Interaktive Tour" Button im Header → Geführte Tour durch alle Tabs\n• Tutorial-Tab: Checklist aller besuchten Bereiche\n• Verschiedene Tour-Modi: Full Tour, Quick Start, Deep Dive\n\nJeder Tab wird beim ersten Besuch als "erledigt" markiert.\nDu kannst die Tour jederzeit neu starten.',
    actions: ['navigate:tutorial'],
  },
  {
    id: 'vip-users',
    title: 'VIP User verwalten',
    keywords: ['vip', 'user', 'benutzer', 'passwort', 'login', 'session', 'zugang', 'mitglied'],
    answer: 'VIP User Management:\n\n1) Öffne Data Explorer → Tabelle "users"\n2) "VIP User anlegen": Username, Email, Passwort eingeben\n3) Passwort Reset: Neues Passwort setzen für bestehende User\n4) Sessions: Aktive Login-Sessions sehen und widerrufen\n\nVIP-User haben Zugang zu:\n• Exklusiven Downloads älterer Sets\n• Premium-Inhalten hinter dem VIP-Gate\n• Vollständigem Archiv',
    actions: ['navigate:explorer'],
  },
  {
    id: 'git-status',
    title: 'Git Status und Versionierung',
    keywords: ['git', 'branch', 'commit', 'push', 'repository', 'repo', 'dirty', 'versionierung'],
    answer: 'Git-Integration:\n\nDer Header zeigt den aktuellen Git-Status:\n• Branch-Name (z.B. main, develop)\n• Dirty/Clean: Ob uncommittete Änderungen existieren\n\nAutomation (in Settings):\n• Auto Commit: Commitet nach Publish automatisch\n• Auto Push: Pusht nach Commit auf Remote\n• Commit Template: Anpassbare Commit-Nachricht\n\nBei "dirty" Status: Prüfe ob unbeabsichtigte Änderungen vorliegen bevor du live gehst.',
  },
  {
    id: 'r2-upload',
    title: 'R2 Audio Upload',
    keywords: ['r2', 'upload', 'cloudflare', 'bucket', 'audio', 'hochladen', 'storage'],
    answer: 'Cloudflare R2 Audio Upload:\n\nVoraussetzungen:\n• AWS Credentials in .env (R2-kompatibel)\n• R2 Bucket muss existieren\n• R2 Prefix in Settings konfiguriert\n\nUpload-Ablauf:\n1) Audio-Datei wird im Import/Batch ausgewählt\n2) Bei "Go Live" wird die Datei zu R2 hochgeladen\n3) Der Audio-Key wird im Manifest gespeichert\n4) Die Website spielt Audio direkt von R2\n\nBei Fehler: Prüfe AWS_ACCESS_KEY_ID und AWS_SECRET_ACCESS_KEY in der .env.',
  },
  {
    id: 'tracklist-editor',
    title: 'Tracklist bearbeiten',
    keywords: ['tracklist', 'track', 'tracks', 'zeit', 'artist', 'titel', 'bearbeiten', 'hinzufügen'],
    answer: 'Tracklist Editor:\n\nIm Set Import Tab:\n• Jeder Track hat: Zeitstempel, Artist, Titel\n• "Track hinzufügen" fügt eine leere Zeile an\n• "x" Button entfernt einen Track\n• Automatische Erkennung aus .txt/.csv Dateien\n\nFormat der Tracklist-Datei:\n• Zeile pro Track: "00:00 Artist - Title"\n• Oder CSV: "time,artist,title"\n• Mixcloud-Format wird ebenfalls unterstützt',
  },
  {
    id: 'vinyl-cover',
    title: 'Vinyl und Cover',
    keywords: ['vinyl', 'cover', 'bild', 'farbe', 'color', 'artwork', 'image'],
    answer: 'Vinyl & Cover Konfiguration:\n\n• Vinyl Color: Farbwähler im Draft-Editor\n• Cover Path: Pfad zum Cover-Bild (relativ zum public-Ordner)\n• Cover Source: Originaldatei vom Windows-Dateisystem\n\nCover-Quellen (Priorität):\n1) Manuell per Drag & Drop\n2) Aus der Audio-Datei extrahiert (wenn "Extract Embedded Cover" an)\n3) Default Cover Path aus Settings\n\nUnterstützte Formate: JPG, PNG, WebP',
  },
  {
    id: 'overview-dashboard',
    title: 'Overview Dashboard',
    keywords: ['overview', 'dashboard', 'überblick', 'status', 'kennzahlen', 'metriken'],
    answer: 'Overview Dashboard:\n\nZeigt den Live-Zustand deiner AIRDOX-Plattform:\n\n• Sets im Manifest: Anzahl publizierter Sets\n• Analytics Events: Gesamtzahl der Event-Logs\n• VIP User: Registrierte Premium-Nutzer\n• Sessions: Aktive Login-Sessions\n\nCommand Center:\n• Repository Status (clean/dirty)\n• Manifest Health (fehlende Stats)\n• Letztes Analytics-Signal\n\n• Top Sets: Tabelle der meistgespielten Sets\n• Recent Analytics: Neueste Events mit Geo/Device\n\nAktionen: Refresh, Demo Import, Analytics, Stats Sync',
    actions: ['navigate:overview'],
  },
  {
    id: 'keyboard-shortcuts',
    title: 'Tastenkürzel',
    keywords: ['tastenkürzel', 'shortcut', 'keyboard', 'hotkey', 'schnelltaste'],
    answer: 'Verfügbare Tastenkürzel:\n\n• Enter im Chat: Nachricht senden\n• Escape: Dialog/Overlay schließen\n\nQuick-Actions im Header:\n• Refresh: Workspace-Status neu laden\n• Import: Set Import öffnen\n• Batch: Batch Import öffnen\n• Assistant: KI-Chat öffnen',
  },
  {
    id: 'troubleshooting',
    title: 'Allgemeine Fehlerbehebung',
    keywords: ['fehler', 'problem', 'funktioniert nicht', 'hilfe', 'bug', 'kaputt', 'hängt', 'crash'],
    answer: 'Allgemeine Fehlerbehebung:\n\n1) Workspace prüfen:\n   → Header zeigt "Workspace verbunden"?\n   → Wenn nicht: Flight Deck → Workspace auswählen\n\n2) Datenbank prüfen:\n   → Header zeigt "DB bereit"?\n   → Wenn nicht: .env Datei und Netzwerk prüfen\n\n3) Git prüfen:\n   → "Git sauber" oder "Git offen"?\n   → Bei "offen": Ungespeicherte Änderungen committen\n\n4) Refresh drücken:\n   → Aktualisiert alle Status-Anzeigen\n\n5) Cache leeren:\n   → System Monitor → Cache löschen\n\n6) Log prüfen:\n   → Publish Log im Set Import Tab zeigt Details',
  },
  {
    id: 'safe-mode',
    title: 'Safe Mode',
    keywords: ['safe mode', 'sicher', 'schutz', 'blockiert', 'risiko'],
    answer: 'Safe Mode:\n\nWenn aktiviert (Advanced Settings):\n• Blockiert Publishes ohne Audio-Quelldatei\n• Verhindert unvollständige Artefakte\n• "Go Live" braucht eine echte Audio Source\n\nWenn deaktiviert:\n• Publish funktioniert auch ohne lokale Audio-Datei\n• Nützlich wenn Audio bereits in R2 liegt\n\nEmpfehlung: Safe Mode AN lassen für normale Workflows.',
  },
  {
    id: 'assistant-help',
    title: 'Was kann der Assistant?',
    keywords: ['was kannst du', 'hilfe', 'funktionen', 'assistant', 'ki', 'bot', 'möglichkeiten', 'allround', 'helfer', 'support', 'fragen beantworten'],
    answer: 'Ich bin der Allround-Helfer für das AIRDOX Flight Deck.\n\nIch kann erklären:\n• alle Tabs und wofür sie da sind\n• Begriffe wie Workspace, Manifest, Draft, R2, Safe Mode, Verify, Snapshot und track_stats\n• Workflows für Import, Batch, Go Live, Analytics, Data Explorer, Design Agent und Marketing Manager\n• Publish-Logs und typische Fehler nach Pipeline-Schritt\n• Datenbanktabellen, Events, Filter und Exporte\n• Settings-Toggles, Git-Status, Deploy-Verhalten und Preflight-Checks\n• Agentenwissen, Reports, latest-Snapshots und Wiki-Pfade\n\nIch kann außerdem:\n• Status aus Workspace/DB/Git zusammenfassen\n• passende Tabs öffnen\n• Refresh, Import und Stats Sync anstoßen\n• konkrete Diagnosepfade liefern, wenn du Fehlertext und letzten Schritt nennst.',
    actions: ['navigate:assistant'],
  },
  {
    id: 'export-data',
    title: 'Daten exportieren',
    keywords: ['export', 'exportieren', 'csv', 'json', 'herunterladen', 'download', 'bericht', 'report'],
    answer: 'Daten Export:\n\nData Explorer:\n• CSV: Tabellarischer Export mit Komma-Trennung\n• JSON: Strukturierter Export mit voller Tiefe\n• Gefilterte Daten: Export respektiert den Suchfilter\n\nAnalytics:\n• "Bericht" Button → Analytics Report als JSON\n\nTipp: Export-Dateien werden im gewählten Ordner gespeichert und danach im Explorer geöffnet.',
    actions: ['navigate:explorer'],
  },
  {
    id: 'subscriber-management',
    title: 'Newsletter Subscriber',
    keywords: ['subscriber', 'newsletter', 'abonnent', 'email', 'mail'],
    answer: 'Newsletter Subscriber verwalten:\n\n1) Data Explorer → Tabelle "subscribers"\n2) Status-Optionen: active, paused, unsubscribed\n3) Email und Status können inline bearbeitet werden\n4) Export als CSV für externe Newsletter-Tools\n\nSubscriber kommen über das Booking-/Kontaktformular der Website.',
    actions: ['navigate:explorer'],
  },
  {
    id: 'first-set',
    title: 'Erstes Set veröffentlichen',
    keywords: ['erstes set', 'anfang', 'starten', 'neu', 'beginnen', 'erstmalig', 'first'],
    answer: 'Dein erstes Set veröffentlichen — Quick Start:\n\n1) ✅ Workspace verbinden (Flight Deck Tab)\n2) ✅ .env mit DB-URL prüfen\n3) ✅ Build/Deploy Commands setzen\n4) 📁 Set Import → Audio + Cover + Tracklist laden\n5) ✏️ Draft prüfen: ID, Titel, Dauer, Tracks\n6) 🎨 Vinyl Color wählen\n7) 🚀 "Alles ausführen & Live" klicken\n8) 🌐 Website im Browser prüfen\n\nBei Problemen: Publish Log im Set Import Tab zeigt jeden Schritt.',
    actions: ['navigate:import'],
  },
];

/**
 * Action commands the assistant can trigger.
 * Each maps to a function the parent component can execute.
 */
export const ASSISTANT_ACTIONS = {
  'navigate:overview': { label: 'Overview öffnen', tabId: 'overview' },
  'navigate:analytics': { label: 'Analytics öffnen', tabId: 'analytics' },
  'navigate:explorer': { label: 'Data Explorer öffnen', tabId: 'explorer' },
  'navigate:import': { label: 'Set Import öffnen', tabId: 'import' },
  'navigate:batch': { label: 'Batch Import öffnen', tabId: 'batch' },
  'navigate:design': { label: 'Design Agent öffnen', tabId: 'design' },
  'navigate:marketing': { label: 'Marketing Manager öffnen', tabId: 'marketing' },
  'navigate:flightdeck': { label: 'Flight Deck öffnen', tabId: 'flightdeck' },
  'navigate:settings': { label: 'Settings öffnen', tabId: 'settings' },
  'navigate:monitor': { label: 'System Monitor öffnen', tabId: 'monitor' },
  'navigate:tutorial': { label: 'Tutorial öffnen', tabId: 'tutorial' },
  'navigate:assistant': { label: 'Assistant öffnen', tabId: 'assistant' },
  'action:refresh': { label: 'Status aktualisieren', action: 'refresh' },
  'action:import': { label: 'Import starten', action: 'import' },
  'action:sync-stats': { label: 'Stats synchronisieren', action: 'syncStats' },
};
