const TAB_LABELS = {
  overview: 'Overview',
  analytics: 'Analytics',
  explorer: 'Data Explorer',
  import: 'Set Import',
  batch: 'Batch Import',
  flightdeck: 'Flight Deck',
  settings: 'Advanced Settings',
  monitor: 'System Monitor',
  tutorial: 'Tutorial',
};

export const TUTORIAL_PRINCIPLES = [
  {
    title: 'Erst Zustand, dann Aktion',
    detail: 'Beginne jede Session in Overview. Wenn Workspace, Branch oder Snapshot nicht stimmen, liefern spaetere Auswertungen und Publishes nur Scheinsicherheit.',
  },
  {
    title: 'Filter vor Interpretation',
    detail: 'In Analytics und Data Explorer gilt dieselbe Regel: erst Zeitraum, Tabelle und Suchraum sauber setzen, dann erst Kennzahlen deuten oder exportieren.',
  },
  {
    title: 'Kleine Zielmengen statt hektischer Massenarbeit',
    detail: 'Gerade im Data Explorer solltest du erst filtern, dann einzelne Zeilen speichern und danach bewusst refreshen. Das senkt das Risiko fuer Fehlkorrekturen deutlich.',
  },
  {
    title: 'Publish endet nicht beim Button',
    detail: 'Ein erfolgreiches Publish ist erst abgeschlossen, wenn du Publish Log, Overview und bei Bedarf Data Explorer gegengeprueft hast.',
  },
  {
    title: 'Interaktive Hilfe statt Feature-Tour',
    detail: 'Die gefuehrten Touren sind absichtlich workflow-orientiert. Sie fuehren dich zu konkreten Aufgaben, nicht nur zu UI-Elementen.',
  },
];

export const TUTORIAL_CHECKLIST = [
  { id: 'overview', label: 'Overview verstanden', tabId: 'overview' },
  { id: 'analytics', label: 'Analytics gelesen', tabId: 'analytics' },
  { id: 'explorer', label: 'Data Explorer geprueft', tabId: 'explorer' },
  { id: 'import', label: 'Set Import nachvollzogen', tabId: 'import' },
  { id: 'batch', label: 'Batch Import geprueft', tabId: 'batch' },
  { id: 'flightdeck', label: 'Flight Deck konfiguriert', tabId: 'flightdeck' },
  { id: 'settings', label: 'Advanced Settings geprueft', tabId: 'settings' },
  { id: 'monitor', label: 'System Monitor gelesen', tabId: 'monitor' },
];

export const TUTORIAL_SECTIONS = [
  {
    id: 'overview',
    tabId: 'overview',
    title: 'Overview',
    shortTitle: 'Systemlage lesen',
    objective: 'Overview ist die Leitwarte fuer Workspace, Manifest, Datenbank und Git. Hier pruefst du zuerst, ob du auf belastbaren Daten arbeitest.',
    whenToUse: 'Immer beim Start einer Session, direkt nach einem Publish, vor einer groesseren Analyse und immer dann, wenn Zahlen ungewoehnlich wirken.',
    beforeYouStart: [
      'Der Workspace sollte verbunden sein, sonst bleibt der Snapshot leer.',
      'Wenn du gerade publiziert hast, plane einen manuellen Refresh ein.',
      'Wenn Git bereits dirty ist, dokumentiere fuer dich, ob du mit einem Zwischenstand arbeitest.',
    ],
    keyFunctions: [
      'Zeigt den Snapshot aus Manifest und Datenbank in einer Management-Sicht.',
      'Listet Top Sets mit Plays, Likes und letztem Wiedergabezeitpunkt.',
      'Zeigt juengste Analytics-Ereignisse fuer schnelle Plausibilitaetschecks.',
      'Zeigt Branch, Dirty-Status, Bookings und Subscribers in einem Block.',
      'Kann ueber `Stats Sync` fehlende `track_stats`-Eintraege nachziehen.',
    ],
    controls: [
      {
        name: 'Refresh',
        area: 'Toolbar',
        purpose: 'Laedt Snapshot, Counts, Git-Status und juengste Aktivitaet neu.',
        howToUse: 'Nutze Refresh nach Publish, Stats Sync oder wenn du Zweifel an der Aktualitaet der Zahlen hast.',
      },
      {
        name: 'Stats Sync',
        area: 'Toolbar',
        purpose: 'Legt fuer Manifest-IDs fehlende `track_stats`-Rows an.',
        howToUse: 'Klicke nur dann, wenn Overview fehlende IDs meldet oder du nach einem neuen Set fehlende Stats siehst.',
      },
      {
        name: 'Metrik-Karten',
        area: 'Mitte',
        purpose: 'Fassen Manifest-Sets, Analytics-Events, VIP-User und Sessions zusammen.',
        howToUse: 'Lies die vier Karten zuerst gemeinsam, nicht isoliert. Eine unplausible Kombination ist oft wichtiger als eine einzelne Zahl.',
      },
      {
        name: 'Top Sets',
        area: 'Linke Spalte',
        purpose: 'Zeigt die meistgenutzten Set-IDs mit Performance-Signal.',
        howToUse: 'Nutze die Liste als erste Antwort auf die Frage, ob neue oder bekannte Sets wirklich genutzt werden.',
      },
      {
        name: 'Git / Runtime',
        area: 'Rechte Spalte',
        purpose: 'Zeigt Branch, Dirty-Status, Status-Zusammenfassung, Bookings und Subscribers.',
        howToUse: 'Beziehe diesen Block in jede Entscheidung ueber Publish, Build oder Datenkorrektur ein.',
      },
      {
        name: 'Recent Analytics',
        area: 'Unterer Bereich',
        purpose: 'Zeigt juengste Events mit Event-Typ, Item-ID, Land, Geraet und Browser.',
        howToUse: 'Lies hier, ob nach einem Release oder Testlauf ueberhaupt aktuelle Events geschrieben wurden.',
      },
    ],
    walkthrough: [
      {
        title: '1. Workspace-Zustand lesen',
        detail: 'Pruefe im Header zuerst `Workspace verbunden` und den Branch. Ohne gueltigen Workspace sind fast alle Folge-Tabs nur eingeschraenkt sinnvoll.',
        action: 'Schaue oben rechts auf Workspace-Pill und Branch-Pill. Wenn `Workspace fehlt` erscheint, unterbrich Analyse oder Publish und verbinde zuerst den richtigen Workspace.',
        expected: 'Workspace ist verbunden und der Branch entspricht dem Arbeitskontext.',
        warning: 'Wenn du im falschen Branch publizierst, ist ein spaeteres Datenbild oft korrekt, aber der Code-Stand nicht.',
      },
      {
        title: '2. Metrik-Karten als Plausibilitaetscheck nutzen',
        detail: 'Die Karten zeigen, ob Manifest, Analytics und Admin-Daten in einem glaubwuerdigen Verhaeltnis stehen.',
        action: 'Vergleiche `Sets im Manifest`, `Analytics Events`, `VIP User` und `Sessions` miteinander und mit deinem aktuellen Arbeitsziel.',
        expected: 'Du erkennst sofort, ob ueberhaupt aktuelle Daten geladen sind und ob die Datenbasis grob plausibel wirkt.',
        warning: 'Viele Sets im Manifest bei gleichzeitig leeren Stats oder Analytics sind ein Signal fuer fehlende Synchronisierung, nicht fuer echtes Nutzungsverhalten.',
      },
      {
        title: '3. Top Sets fachlich lesen',
        detail: 'Top Sets liefern nicht nur ein Ranking, sondern auch einen Abgleich zwischen Erwartung und Wirklichkeit.',
        action: 'Pruefe, ob neue Sets auftauchen, ob bekannte Gewinner stabil bleiben und ob `Last Played` zeitlich zur aktuellen Lage passt.',
        expected: 'Du kannst sofort sagen, welche Set-IDs aktuell tragen und welche eher inaktiv sind.',
        warning: 'Ein hoher Play-Wert ohne aktuelles `Last Played` kann auf Altlasten statt auf frische Traction hinweisen.',
      },
      {
        title: '4. Fehlende Stats nachziehen',
        detail: 'Wenn Overview fehlende `track_stats` IDs meldet, ist dein Datenmodell nicht vollstaendig synchron.',
        action: 'Klicke `Stats Sync`, warte auf die Rueckmeldung und fuehre danach `Refresh` aus.',
        expected: 'Fehlende IDs verschwinden aus der Warnung, und neue Sets sind in `track_stats` sichtbar.',
        warning: 'Stats Sync ersetzt keine fachliche Kontrolle. Danach solltest du die neuen Zeilen im Explorer gegenpruefen.',
      },
      {
        title: '5. Recent Analytics als Live-Signal lesen',
        detail: 'Hier pruefst du, ob Event-Logging technisch und fachlich lebt.',
        action: 'Schaue auf Event-Typ, Item-ID, Land, Geraet und Browser. Vergleiche das mit dem, was du nach dem letzten Test oder Release erwartest.',
        expected: 'Du kannst beurteilen, ob aktuelle Aktivitaet vorhanden ist und ob die Event-Details plausibel aussehen.',
        warning: 'Ein leeres `Recent Analytics` ist nicht automatisch ein Fehler, aber es muss zu deinem Zeitraum und deiner Erwartung passen.',
      },
      {
        title: '6. Git- und Runtime-Lage absichern',
        detail: 'Overview ist die letzte schnelle Stelle, an der du Publish oder DB-Eingriffe noch bewusst abbrechen kannst.',
        action: 'Wenn `Dirty = Ja`, entscheide aktiv, ob du mit diesem Stand weiterarbeiten willst oder zuerst committen, staschen oder dokumentieren musst.',
        expected: 'Du kennst deinen technischen Ausgangspunkt vor jeder produktiven Aktion.',
        warning: 'Unguesteuerte Kombinationen aus Dirty Worktree, Auto Commit und Auto Push erzeugen schnell unlesbare Release-Verlaeufe.',
      },
    ],
    practiceTasks: [
      'Finde den aktiven Branch und sage fuer dich, ob er zum heutigen Arbeitsziel passt.',
      'Pruefe, ob die Zahl der Manifest-Sets grob zu den sichtbaren Top Sets passt.',
      'Suche im Bereich `Recent Analytics` ein Event und lies daraus Item-ID, Land und Geraet ab.',
      'Fuehre nur dann einen Stats Sync aus, wenn eine fehlende ID angezeigt wird, und kontrolliere danach per Refresh den Zustand erneut.',
    ],
    commonMistakes: [
      'Overview zu ueberspringen und direkt im Explorer zu korrigieren.',
      'Dirty-Status zu ignorieren, obwohl im selben Lauf publiziert werden soll.',
      'Leere Recent-Analytics-Liste als Fehler zu deuten, ohne Zeitraum und Erwartung zu pruefen.',
    ],
    tips: [
      'Overview ist kein nettes Dashboard, sondern die Freigabestelle fuer alles, was danach kommt.',
      'Vor jedem Export oder Publish lohnt sich ein letzter Blick auf `Top Sets` und `Git / Runtime`.',
    ],
    successChecks: [
      'Workspace ist verbunden.',
      'Branch und Dirty-Status sind verstanden.',
      'Fehlende `track_stats`-IDs wurden abgeglichen oder bewusst notiert.',
      'Aktuelle Analytics-Aktivitaet ist sichtbar oder nachvollziehbar nicht vorhanden.',
    ],
    relatedTabs: [
      'Analytics fuer fachliche Verdichtung nach Zeitraum und Filter.',
      'Data Explorer fuer Rohdatenkontrolle und Korrekturen.',
      'Flight Deck, wenn Workspace oder Publish-Strategie angepasst werden muss.',
    ],
  },
  {
    id: 'analytics',
    tabId: 'analytics',
    title: 'Analytics',
    shortTitle: 'Kennzahlen auswerten',
    objective: 'Analytics verdichtet Nutzungsdaten zu einer fachlichen Sicht auf Reichweite, Nutzung, Resonanz und Muster nach Land, Geraet und Zeit.',
    whenToUse: 'Fuer Reporting, Kampagnenkontrolle, Release-Review, Plausibilisierung von Nutzungsverhalten und als Vorstufe fuer Exporte.',
    beforeYouStart: [
      'Pruefe in Overview, ob ueberhaupt aktuelle Analytics vorhanden sind.',
      'Setze dir vorab eine konkrete Frage, z. B. `Welches Set performt im letzten Monat auf Mobile in DE?`.',
      'Arbeite Vergleichsfaelle immer mit identischen Zeitraeumen aus.',
    ],
    keyFunctions: [
      'Zeigt Kernmetriken fuer Gesamtaufrufe, Plays, Likes und Engagement Rate.',
      'Bietet Datepicker und Filter fuer Event-Typ, Geraet und Land.',
      'Visualisiert Top Sets, Geo-Verteilung, Geraete-Breakdown und Tageszeit-Peaks.',
      'Zeigt eine kompakte Event-Typ-Uebersicht fuer die aktuelle Analyse.',
      'Kann ueber `Bericht` einen Analytics-Report exportieren.',
    ],
    controls: [
      {
        name: 'Aktualisieren',
        area: 'Toolbar',
        purpose: 'Laedt das Analytics-Dataset neu.',
        howToUse: 'Nutze den Button vor einer neuen Analyse oder wenn du nach externen Tests frische Daten erwartest.',
      },
      {
        name: 'Bericht',
        area: 'Toolbar',
        purpose: 'Exportiert den aktuellen Analytics-Bericht.',
        howToUse: 'Exportiere erst, nachdem Zeitraum und Filter bewusst gesetzt wurden.',
      },
      {
        name: 'Von / Bis',
        area: 'Zeitraum & Filter',
        purpose: 'Begrenzt den fachlichen Analysezeitraum.',
        howToUse: 'Arbeite mit klaren Zeitfenstern wie letzte 7 Tage, letzter Monat oder Kampagnenzeitraum.',
      },
      {
        name: 'Event-Typ',
        area: 'Zeitraum & Filter',
        purpose: 'Fokussiert auf `play`, `like`, `dislike` oder `view`.',
        howToUse: 'Nutze `view` fuer Reichweite, `play` fuer echte Nutzung, `like` und `dislike` fuer Resonanz.',
      },
      {
        name: 'Geraet',
        area: 'Zeitraum & Filter',
        purpose: 'Trennt mobile, desktop- und tablet-Nutzung.',
        howToUse: 'Besonders hilfreich, wenn du vermutest, dass ein Verhalten oder Problem geraetespezifisch ist.',
      },
      {
        name: 'Land',
        area: 'Zeitraum & Filter',
        purpose: 'Grenzt die Analyse geographisch ein.',
        howToUse: 'Vergleiche nach dem Setzen des Landes Geo-Verteilung, Top Sets und Engagement erneut im Zusammenhang.',
      },
      {
        name: 'Top Sets / Geo / Device / Tageszeit',
        area: 'Analyseflaeche',
        purpose: 'Zeigt vier Blickwinkel auf dasselbe Datenbild.',
        howToUse: 'Lies diese Visualisierungen nacheinander, nicht durcheinander. Erst Metriken, dann Sets, dann Verteilungen.',
      },
    ],
    walkthrough: [
      {
        title: '1. Zeitraum zuerst fixieren',
        detail: 'Der Zeitraum ist der wichtigste Kontext fuer jede Zahl in diesem Tab.',
        action: 'Setze `Von` und `Bis` bewusst, bevor du eine einzige Kennzahl interpretierst.',
        expected: 'Du kannst jede spaetere Aussage mit einem klaren Zeitraum belegen.',
        warning: 'Unbewusst offene oder zu breite Zeitraeume machen Vergleiche fast wertlos.',
      },
      {
        title: '2. Event-Typ fachlich einordnen',
        detail: 'Nicht jede Analyse braucht `Alle`.',
        action: 'Waehle gezielt `play`, `view`, `like` oder `dislike`, wenn du Verhalten genauer verstehen willst.',
        expected: 'Du unterscheidest sauber zwischen Reichweite, echter Nutzung und Resonanz.',
        warning: 'Viele Views bei wenigen Plays sind keine gute Performance, sondern ein Aktivierungsproblem.',
      },
      {
        title: '3. Metrik-Karten in Relation lesen',
        detail: 'Die oberen vier Werte haben nur gemeinsam Aussagekraft.',
        action: 'Vergleiche Gesamtaufrufe, Plays, Likes und Engagement Rate miteinander statt jeden Wert isoliert zu beurteilen.',
        expected: 'Du erkennst Muster wie hohe Sichtbarkeit bei schwacher Aktivierung oder solide Nutzung mit schwacher Resonanz.',
        warning: 'Eine hohe Engagement Rate bei sehr kleinen Datenmengen kann leicht ueberinterpretiert werden.',
      },
      {
        title: '4. Top Sets priorisieren',
        detail: 'Die Top-Set-Liste ist dein direkter Hebel fuer Priorisierung, Promotion und Kontrolle.',
        action: 'Pruefe, welche IDs oben stehen, welche fehlen und ob neue Releases bereits sichtbar werden.',
        expected: 'Du kannst klar benennen, welche Sets derzeit tragen und welche hinter Erwartung bleiben.',
        warning: 'Top Sets ohne Kontext aus Zeitraum und Land werden schnell falsch gelesen.',
      },
      {
        title: '5. Geo- und Device-Bild zusammendenken',
        detail: 'Laender und Geraete erzaehlen oft dieselbe Geschichte aus zwei Blickwinkeln.',
        action: 'Schaue zuerst auf Geo-Verteilung, dann auf Geraete-Breakdown und verknuepfe die Ergebnisse mit deiner Produktfrage.',
        expected: 'Du erkennst, ob bestimmte Laender oder Endgeraete das Bild dominieren.',
        warning: 'Ein Geraeteproblem laesst sich nicht in Analytics loesen, aber hier meist zum ersten Mal sichtbar machen.',
      },
      {
        title: '6. Tageszeit fuer Timing-Fragen nutzen',
        detail: 'Die Tageszeit-Verteilung beantwortet die Frage, wann Nutzung tatsaechlich stattfindet.',
        action: 'Lies den Peak-Wert und vergleiche ihn mit deinen Release- oder Promo-Zeitpunkten.',
        expected: 'Du bekommst eine belastbare Tendenz fuer guenstige Veroeffentlichungsfenster.',
        warning: 'Der Peak ist nur dann sinnvoll, wenn der gewaehlte Zeitraum genug Volumen hat.',
      },
      {
        title: '7. Bericht erst am Ende exportieren',
        detail: 'Ein guter Export ist das Ergebnis einer fertigen Analyse, nicht ihr Start.',
        action: 'Klicke `Bericht` erst dann, wenn du Zeitraum, Event-Typ, Geraet und Land bewusst gesetzt hast.',
        expected: 'Dein Report entspricht genau dem Analysekontext, den du spaeter kommunizieren willst.',
        warning: 'Export vor Filterung ist einer der haeufigsten Gruende fuer unbrauchbare Reports.',
      },
    ],
    practiceTasks: [
      'Setze den Zeitraum auf die letzten 30 Tage und pruefe, wie sich die Top Sets dadurch veraendern.',
      'Filtere auf `play` und schaue, ob dasselbe Set weiterhin fuehrt wie bei `all`.',
      'Stelle `Geraet = mobile` und `Land = DE` ein und lies danach Top Sets, Geo und Device erneut.',
      'Notiere fuer dich, was der sichtbare Peak in der Tageszeit-Verteilung fuer einen Release-Termin bedeuten koennte.',
    ],
    commonMistakes: [
      'Erst exportieren und danach filtern.',
      'Engagement Rate ohne absolutes Volumen zu interpretieren.',
      'Land- und Device-Filter zu setzen, aber anschliessend die Werte so zu lesen, als waeren sie global.',
    ],
    tips: [
      'Arbeite fuer Vorher-Nachher-Vergleiche immer mit denselben Filtern.',
      'Wenn Werte leer wirken, gehe nicht sofort von einem Bug aus. Erst `Aktualisieren`, dann Overview gegenpruefen.',
    ],
    successChecks: [
      'Der Zeitraum ist bewusst gesetzt.',
      'Event-Typ, Land und Geraet wurden nur dann gesetzt, wenn sie fachlich gebraucht werden.',
      'Du kennst die aktuell staerksten Sets fuer den gewaehlten Kontext.',
      'Ein Export wurde erst nach finalem Filterzustand erzeugt.',
    ],
    relatedTabs: [
      'Overview fuer Plausibilitaetscheck vor der Analyse.',
      'Data Explorer fuer Rohdatenkontrolle hinter auffaelligen Mustern.',
      'System Monitor, wenn Analytics-Ladezeiten oder Query-Verhalten auffaellig werden.',
    ],
  },
  {
    id: 'explorer',
    tabId: 'explorer',
    title: 'Data Explorer',
    shortTitle: 'Datenbank pflegen',
    objective: 'Der Data Explorer ist die operative Arbeitsflaeche fuer Tabellen, Rohdatenkontrolle, gezielte Korrekturen, Exporte und lesende SQL-Abfragen.',
    whenToUse: 'Fuer Datenpflege, Rohdaten-Pruefungen, User-Administration, Session-Kontrolle und Reporting-Exporte.',
    beforeYouStart: [
      'Klaere vorher in Analytics oder Overview, welche Frage du beantworten willst.',
      'Waehle dann bewusst die richtige Tabelle statt blind zu suchen.',
      'Plane nach jeder Aenderung einen Refresh ein.',
    ],
    keyFunctions: [
      'Wechselt zwischen `track_stats`, `analytics_logs`, `bookings`, `subscribers`, `users` und `sessions`.',
      'Filtert tabellenweit ueber die Suchleiste.',
      'Exportiert die aktuelle Auswahl als CSV oder JSON.',
      'Erlaubt Inline-Bearbeitung in `track_stats` und `subscribers`.',
      'Erlaubt VIP-User-Anlage, Passwort-Reset und Session-Revoke.',
      'Fuehrt ausschliesslich Read-only SQL ueber `SELECT`, `WITH` oder `EXPLAIN` aus.',
    ],
    controls: [
      {
        name: 'Tabellen-Dropdown',
        area: 'Toolbar',
        purpose: 'Wechselt die aktive Tabelle und damit die gesamte Arbeitsflaeche.',
        howToUse: 'Stelle immer zuerst die Zieltabelle ein. Alle weiteren Aktionen haengen von dieser Auswahl ab.',
      },
      {
        name: 'Filtern...',
        area: 'Toolbar',
        purpose: 'Grenzt die sichtbare Menge clientseitig ein.',
        howToUse: 'Nutze das Suchfeld vor Edits und vor Exporten, damit du nur auf die beabsichtigte Teilmenge schaust.',
      },
      {
        name: 'CSV / JSON',
        area: 'Toolbar',
        purpose: 'Exportiert die aktuell gefilterten Zeilen.',
        howToUse: 'CSV fuer Tabellenarbeit, JSON fuer technische Weiterverarbeitung. Immer erst nach gesetztem Filter exportieren.',
      },
      {
        name: 'Refresh',
        area: 'Toolbar',
        purpose: 'Laedt die aktuelle Tabelle neu.',
        howToUse: 'Pflichtschritt nach `Save Row`, `Save Subscriber`, User-Loeschung oder Session-Revoke.',
      },
      {
        name: 'Track Stats Editor',
        area: 'track_stats',
        purpose: 'Aendert Plays, Likes, Dislikes und Last Played pro Zeile.',
        howToUse: 'Bearbeite nur klar begrenzte Datensaetze und speichere jede Zeile einzeln ueber `Save Row`.',
      },
      {
        name: 'Subscriber Editor',
        area: 'subscribers',
        purpose: 'Pflegt E-Mail und Status.',
        howToUse: 'Nutze den Status nur mit klarer Absicht, z. B. `active`, `paused` oder `unsubscribed`.',
      },
      {
        name: 'User Admin',
        area: 'users',
        purpose: 'Legt VIP-User an, setzt Passwoerter zurueck und loescht User.',
        howToUse: 'Dokumentiere administrative Eingriffe, vor allem Passwort-Resets und Kontoloeschungen.',
      },
      {
        name: 'Sessions Admin',
        area: 'sessions',
        purpose: 'Zeigt Sessions und erlaubt den Widerruf einzelner Sitzungen.',
        howToUse: 'Widerrufe Sessions gezielt bei Support- oder Sicherheitsfaellen.',
      },
      {
        name: 'Read-only SQL',
        area: 'Unterer Bereich',
        purpose: 'Erlaubt gezielte Auswertungen ohne Schreibzugriff.',
        howToUse: 'Nutze nur `SELECT`, `WITH` und `EXPLAIN` und lies danach `rowCount` sowie die JSON-Antwort.',
      },
    ],
    walkthrough: [
      {
        title: '1. Zieltabelle festlegen',
        detail: 'Der Explorer ist nur dann sicher, wenn du genau weisst, in welcher Tabelle du arbeitest.',
        action: 'Waehle im Dropdown zuerst die Tabelle, die fachlich zu deiner Frage passt.',
        expected: 'Die UI wechselt in den passenden Bearbeitungsmodus fuer die Tabelle.',
        warning: 'Viele Fehler passieren nicht im Speichern, sondern weil in der falschen Tabelle gearbeitet wurde.',
      },
      {
        title: '2. Suchraum begrenzen',
        detail: 'Die Filterleiste ist dein Schutz gegen versehentliche Arbeit an zu grossen Datenmengen.',
        action: 'Gib Set-ID, Event-Typ, E-Mail, Username oder andere markante Begriffe in `Filtern...` ein.',
        expected: 'Du arbeitest mit einer ueberschaubaren Teilmenge statt mit der gesamten Tabelle.',
        warning: 'Export und visuelle Kontrolle werden unbrauchbar, wenn du den Filter zu spaet setzt.',
      },
      {
        title: '3. track_stats richtig lesen und speichern',
        detail: 'Diese Tabelle spiegelt Set-Performance auf Aggregationsebene.',
        action: 'Pruefe `plays`, `likes`, `dislikes` und `last_played_at`, aendere nur bei klarem Grund und speichere per `Save Row`.',
        expected: 'Die geaenderte Zeile ist nach Refresh mit dem neuen Wert sichtbar.',
        warning: 'Manuelle Aenderungen in `track_stats` sollten die Ausnahme sein und spaeter gegen Analytics eingeordnet werden.',
      },
      {
        title: '4. analytics_logs fuer Rohereignisse nutzen',
        detail: 'Hier siehst du, was wirklich als Event geschrieben wurde.',
        action: 'Filtere nach Event-Typ, Item-ID, Land, Geraet oder Browser und vergleiche das Rohbild mit der Analytics-Zusammenfassung.',
        expected: 'Du erkennst, ob ein Muster echt ist oder nur in der Aggregation auffaellig aussieht.',
        warning: 'Hohe Event-Zahlen ohne Bezug zur Item-ID helfen fachlich kaum weiter.',
      },
      {
        title: '5. subscribers, users und sessions administrativ behandeln',
        detail: 'Diese Tabellen sind weniger Analyse, mehr Betrieb.',
        action: 'Pflege Statuswerte, lege VIP-User an, setze Passwoerter zurueck oder widerrufe Sessions nur mit klarer Absicht.',
        expected: 'Administrative Daten sind sauber und fuer Support oder Security nachvollziehbar.',
        warning: 'Gerade Passwort-Reset und User-Loeschung gehoeren nicht in hektische Nebenhandlungen.',
      },
      {
        title: '6. Read-only SQL gezielt einsetzen',
        detail: 'SQL ist hier fuer Sonderfragen gedacht, nicht fuer Mutproben.',
        action: 'Formuliere lesende Abfragen, fuehre sie mit `Run Query` aus und lies danach `rowCount` und JSON-Ergebnis.',
        expected: 'Du beantwortest Sonderfragen schnell, ohne Produktionsdaten zu veraendern.',
        warning: 'Wenn eine Query nicht klar lesend ist, gehoert sie nicht in diesen Bereich.',
      },
      {
        title: '7. Export erst mit Kontext',
        detail: 'Ein guter Export braucht die richtige Tabelle und den richtigen Filterzustand.',
        action: 'Pruefe Filter und sichtbare Menge, exportiere dann CSV oder JSON und kontrolliere anschliessend die exportierte Zielmenge.',
        expected: 'Dein Export enthaelt nur die beabsichtigten Datensaetze.',
        warning: 'Ungefilterter JSON-Export produziert schnell unhandliche oder missverstandene Dateien.',
      },
    ],
    practiceTasks: [
      'Waehle `track_stats` und suche gezielt nach einer einzelnen Set-ID.',
      'Wechsle zu `analytics_logs` und pruefe, ob fuer dieselbe Set-ID juengste Events sichtbar sind.',
      'Oeffne `users` und identifiziere, welche Aktionen dort administrativ moeglich sind.',
      'Formuliere eine Read-only SQL-Abfrage, die die 10 neuesten Analytics-Ereignisse zeigt.',
    ],
    commonMistakes: [
      'In einer zu grossen Menge arbeiten und erst spaeter filtern.',
      'Manuelle Stats-Korrekturen vorzunehmen, ohne vorher das Rohbild in `analytics_logs` zu pru fen.',
      'CSV oder JSON zu exportieren, obwohl noch die falsche Tabelle aktiv ist.',
    ],
    tips: [
      'Filtere fuer Korrekturen lieber zu eng als zu breit.',
      'Fuer Tabellenarbeit eignet sich CSV, fuer technische Nachbearbeitung JSON.',
    ],
    successChecks: [
      'Die richtige Tabelle ist aktiv.',
      'Der Filter begrenzt die Zielmenge sinnvoll.',
      'Gespeicherte Aenderungen wurden per Refresh gegengeprueft.',
      'SQL wurde nur lesend eingesetzt.',
    ],
    relatedTabs: [
      'Analytics fuer fachliche Voranalyse.',
      'Overview fuer Plausibilitaetscheck vor manuellen Eingriffen.',
      'System Monitor, wenn Explorer oder Queries spuerbar traege werden.',
    ],
  },
  {
    id: 'import',
    tabId: 'import',
    title: 'Set Import',
    shortTitle: 'Ein Set publizieren',
    objective: 'Set Import ist der produktive Pfad fuer einzelne Releases mit Audio, Cover, Tracklist, Draft-Feldern und Publish Log.',
    whenToUse: 'Fuer jeden einzelnen neuen oder aktualisierten Release, wenn du die Metadaten kontrolliert pflegen und publizieren willst.',
    beforeYouStart: [
      'Pruefe in Overview und Flight Deck, ob Workspace und Automation passen.',
      'Lege Audio, Cover und optional Tracklist so bereit, dass du sie gemeinsam pruefen kannst.',
      'Bestimme die finale Set-ID frueh, weil sie Manifest, Dateiname und Stats verknuepft.',
    ],
    keyFunctions: [
      'Nimmt Dateien per Drag-and-Drop oder Dateiauswahl entgegen.',
      'Fuellt einen Draft mit ID, Titel, Datum, Datei, Dauer, Farbe, Cover und Publish-Datum.',
      'Zeigt Warnungen vor dem Publish.',
      'Erlaubt vollstaendige Bearbeitung der Tracklist.',
      'Fuehrt Publish aus und zeigt jeden Schritt im Publish Log.',
    ],
    controls: [
      {
        name: 'Dropzone / Dateien waehlen',
        area: 'Kopfbereich',
        purpose: 'Liest Audio-, Cover- und Tracklist-Dateien ein.',
        howToUse: 'Ziehe Dateien direkt hinein oder nutze `Dateien waehlen`, wenn du sauber aus dem Dateisystem auswaehlen willst.',
      },
      {
        name: 'Demo Import',
        area: 'Kopfbereich',
        purpose: 'Laedt im Browser-Modus einen Demo-Draft.',
        howToUse: 'Nur fuer Mock- oder Demo-Situationen sinnvoll, nicht fuer produktive Publishes.',
      },
      {
        name: 'Warnings',
        area: 'Alert-Block',
        purpose: 'Zeigt fehlende oder unklare Informationen vor dem Publish.',
        howToUse: 'Arbeite die Liste zuerst ab. Warnungen sind kein Dekoelement.',
      },
      {
        name: 'Draft-Felder',
        area: 'Linke Spalte',
        purpose: 'Steuern Manifest, Dateireferenz, Farbe, Sichtbarkeit und Publish-Datum.',
        howToUse: 'Pruefe vor allem `ID`, `Datei`, `Dauer`, `Cover Path`, `Published At` und `New Badge aktiv`.',
      },
      {
        name: 'Audio Source / Cover Source',
        area: 'Linke Spalte unten',
        purpose: 'Zeigen die urspruenglichen Quelldateien.',
        howToUse: 'Nutze die read-only Felder zur Kontrolle, ob wirklich die erwarteten Quelldateien geladen wurden.',
      },
      {
        name: 'Tracklist',
        area: 'Rechte Spalte',
        purpose: 'Pflegt Zeit, Artist und Titel pro Track.',
        howToUse: 'Gehe Track fuer Track durch und fuege fehlende Zeilen nur bewusst hinzu.',
      },
      {
        name: 'Publish Set',
        area: 'Linke Spalte unten',
        purpose: 'Startet den produktiven Publish-Lauf.',
        howToUse: 'Der Button sollte erst genutzt werden, wenn Kernfelder gesetzt und Warnungen bearbeitet sind.',
      },
      {
        name: 'Publish Log',
        area: 'Unterer Bereich',
        purpose: 'Dokumentiert jeden Publish-Schritt mit Status und Zeit.',
        howToUse: 'Lies den gesamten Lauf, nicht nur die Endmeldung. Gerade Zwischenfehler sind dort sichtbar.',
      },
    ],
    walkthrough: [
      {
        title: '1. Quelldateien einlesen',
        detail: 'Der Import beginnt mit den realen Dateien, nicht mit manueller Feldpflege.',
        action: 'Ziehe Audio, Cover und optional Tracklist in die Dropzone oder waehle sie ueber den Button aus.',
        expected: 'Der Draft wird automatisch vorbefuellt und Source-Felder zeigen die geladenen Dateien.',
        warning: 'Ein falsches Audiofile faellt spaeter oft zu spaet auf, wenn du die Source-Felder nicht pruefst.',
      },
      {
        title: '2. Warnungen zuerst lesen',
        detail: 'Die Warnungen sind dein Fruehwarnsystem fuer fehlende Daten oder unklare Ableitungen.',
        action: 'Pruefe jede Warnung und entscheide, ob du sie durch bessere Eingaben aufloesen musst.',
        expected: 'Der Draft ist fachlich eindeutiger und publish-faehig.',
        warning: 'Warnungen zu ignorieren fuehrt spaeter fast immer zu Nacharbeit im Manifest oder Explorer.',
      },
      {
        title: '3. Draft-Felder validieren',
        detail: 'Die Automatik hilft, ersetzt aber keine redaktionelle Kontrolle.',
        action: 'Kontrolliere ID, Titel, Date Label, Datei, Dauer, Vinyl Color, Cover Path, Published At und `New Badge aktiv`.',
        expected: 'Der Draft bildet das Release technisch und redaktionell sauber ab.',
        warning: 'Gerade `ID` und `Datei` sind strukturell wichtig. Fehler dort ziehen sich durch mehrere Systeme.',
      },
      {
        title: '4. Tracklist bereinigen',
        detail: 'Die Tracklist ist spaeter direkt sichtbar und darf nicht schlampig publiziert werden.',
        action: 'Gehe jede Zeile mit Zeit, Artist und Titel durch. Entferne Leerzeilen, korrigiere Tippfehler und fuege fehlende Tracks hinzu.',
        expected: 'Die Tracklist ist vollstaendig, lesbar und zeitlich plausibel.',
        warning: 'Eine technisch erfolgreiche Veroeffentlichung mit schlechter Tracklist ist fachlich trotzdem schlecht.',
      },
      {
        title: '5. Publish bewusst starten',
        detail: 'Publish ist der Uebergang von lokaler Vorbereitung zu produktiver Aenderung.',
        action: 'Klicke `Publish Set` erst dann, wenn Kernfelder gesetzt und die Tracklist fertig ist.',
        expected: 'Der Publish-Lauf startet und das Log fuellt sich mit Schritten.',
        warning: 'Wenn der Button nur knapp freigeschaltet ist, heisst das nicht automatisch, dass der Draft schon gut genug ist.',
      },
      {
        title: '6. Publish Log bis zum Ende lesen',
        detail: 'Das Log zeigt nicht nur Erfolg, sondern auch Teilfehler und Reihenfolge.',
        action: 'Lies Status, Detail und Zeit pro Schritt und notiere, ob Cover, Audio, Manifest, Stats, Build oder Deploy Auffaelligkeiten hatten.',
        expected: 'Du weisst genau, welcher Teil des Publishes sauber gelaufen ist und welcher nicht.',
        warning: 'Eine gruen klingende Abschlussmeldung ersetzt nicht den Blick auf jeden Log-Eintrag.',
      },
      {
        title: '7. Ergebnis nachkontrollieren',
        detail: 'Ein Release ist erst abgeschlossen, wenn Folge-Tabs das Ergebnis bestaetigen.',
        action: 'Wechsle in Overview und danach bei Bedarf in Data Explorer, um Manifest, `track_stats` und Git-Lage zu kontrollieren.',
        expected: 'Das neue Set ist in den Folge-Tabs sichtbar und technisch plausibel.',
        warning: 'Ohne Nachkontrolle merkst du Fehler oft erst, wenn Frontend oder Reporting bereits darauf aufsetzen.',
      },
    ],
    practiceTasks: [
      'Lade ein Test-Set und pruefe, welche Felder automatisch vorbelegt werden.',
      'Aendere eine Tracklist-Zeile bewusst und kontrolliere, ob die Aenderung sichtbar bleibt.',
      'Pruefe vor dem Publish, ob `Audio Source` und `Cover Source` auf die erwarteten Quelldateien zeigen.',
      'Lies nach dem Publish das Log Zeile fuer Zeile und formuliere fuer dich, welche Schritte erfolgreich waren.',
    ],
    commonMistakes: [
      'Die automatisch ermittelte ID ungeprueft zu uebernehmen.',
      'Warnungen zu ueberspringen, weil der Publish-Button schon aktiv ist.',
      'Nach erfolgreichem Publish nicht mehr in Overview oder Explorer zu schauen.',
    ],
    tips: [
      'Die Set-ID sollte frueh final sein.',
      'Tracklist-Qualitaet ist Teil des Releases, nicht Beiwerk.',
    ],
    successChecks: [
      'Warnungen sind bearbeitet oder bewusst akzeptiert.',
      'Draft und Tracklist sind redaktionell sauber.',
      'Publish Log zeigt keine unerwarteten Fehler.',
      'Das neue Set ist in den Folge-Tabs sichtbar.',
    ],
    relatedTabs: [
      'Flight Deck fuer Publish-Automation und Ziel-Workspace.',
      'Overview fuer Nachkontrolle.',
      'Data Explorer fuer `track_stats`- und Rohdatenpruefung nach dem Publish.',
    ],
  },
  {
    id: 'batch',
    tabId: 'batch',
    title: 'Batch Import',
    shortTitle: 'Volumen verarbeiten',
    objective: 'Batch Import ist die Queue-basierte Arbeitsflaeche fuer groessere Eingangsmengen an Audio-, Cover- und Tracklist-Dateien.',
    whenToUse: 'Wenn mehrere Dateien gesammelt vorbereitet, beobachtet und in einem Lauf verarbeitet werden sollen.',
    beforeYouStart: [
      'Nutze Batch fuer Volumen, nicht fuer die letzte redaktionelle Feinkontrolle.',
      'Plane fuer Fehlerfaelle anschliessend gezielte Nacharbeit ueber Set Import ein.',
      'Behalte parallel den System Monitor im Blick, wenn die Queue gross wird.',
    ],
    keyFunctions: [
      'Nimmt mehrere Dateien per Drag-and-Drop in die Queue auf.',
      'Zeigt Sammelstatistiken fuer Erfolg, Pending und Fehler.',
      'Zeigt Gesamtfortschritt des laufenden Batches.',
      'Erlaubt Entfernen offener Queue-Eintraege und Aufraeumen fertiger Items.',
      'Zeigt Fehler in einer eigenen Zusammenfassung.',
    ],
    controls: [
      {
        name: 'Start / Pause',
        area: 'Toolbar',
        purpose: 'Startet oder pausiert den Stapellauf.',
        howToUse: 'Starte erst, wenn die Queue inhaltlich geprueft wurde. Pause ist fuer Kontrolle gedacht, nicht fuer dauerhaften Betriebszustand.',
      },
      {
        name: 'Status-Chips',
        area: 'Toolbar',
        purpose: 'Zeigen sofort, wie viele Items erfolgreich, offen oder fehlerhaft sind.',
        howToUse: 'Lies diese Zahlen immer im Zusammenhang mit dem Gesamtfortschritt.',
      },
      {
        name: 'Batch-Fortschritt',
        area: 'Oberer Mittelbereich',
        purpose: 'Visualisiert aktuellen Lauf gegen Gesamtmenge.',
        howToUse: 'Besonders wichtig bei grossen Chargen oder wenn du Wartezeit abschaetzen willst.',
      },
      {
        name: 'Drag-Drop-Zone',
        area: 'Mitte',
        purpose: 'Nimmt Audio-, Cover- und Tracklist-Dateien gesammelt auf.',
        howToUse: 'Ziehe Dateien hinein oder nutze den Auswahl-Button. Pruefe danach die Queue, nicht nur die Dropzone.',
      },
      {
        name: 'Import-Queue',
        area: 'Unterer Bereich',
        purpose: 'Zeigt jeden Eintrag mit Status, optionalem Fortschritt und Nachricht.',
        howToUse: 'Arbeite die Queue als Arbeitsliste: offene entfernen, Fehler identifizieren, Erfolge aufraeumen.',
      },
      {
        name: 'Fertige loeschen',
        area: 'Queue-Kopf',
        purpose: 'Entfernt abgeschlossene Eintraege aus der Liste.',
        howToUse: 'Nutze die Funktion, wenn du nur noch offene Arbeit sichtbar haben willst.',
      },
      {
        name: 'Fehlerzusammenfassung',
        area: 'Unterster Bereich',
        purpose: 'Buesndelt alle Items mit Fehlerstatus.',
        howToUse: 'Nutze den Bereich als Nacharbeitsliste fuer Einzelkorrekturen.',
      },
    ],
    walkthrough: [
      {
        title: '1. Dateien gesammelt aufnehmen',
        detail: 'Der Batch lebt von sauber vorbereiteten Eingangsmengen.',
        action: 'Ziehe mehrere Dateien in die Dropzone oder waehle sie gesammelt aus.',
        expected: 'Die Queue fuellt sich mit `pending`-Eintraegen.',
        warning: 'Falsch benannte Dateien oder gemischte Chaoten-Queues kosten spaeter mehr Zeit als ein sauberer Vorabcheck.',
      },
      {
        title: '2. Queue vor dem Start lesen',
        detail: 'Jetzt ist der letzte einfache Punkt fuer Korrektur ohne Seiteneffekt.',
        action: 'Pruefe Dateinamen, Anzahl und offensichtliche Ausreisser und entferne problematische Eintraege vor dem Start.',
        expected: 'Die Queue enthaelt nur die Dateien, die wirklich in diesen Lauf gehoeren.',
        warning: 'Batch-Fehler sind oft Dateifehler, nicht Systemfehler.',
      },
      {
        title: '3. Lauf starten und Fortschritt beobachten',
        detail: 'Ab jetzt wird aus Vorbereitung produktive Verarbeitung.',
        action: 'Klicke `Start` und beobachte Statuswechsel von `pending` nach `processing` und `success` oder `error`.',
        expected: 'Der Gesamtfortschritt steigt und einzelne Items bekommen Statusmeldungen.',
        warning: 'Ein laufender Batch sollte nicht blind im Hintergrund gelassen werden, wenn du auf Fehler reagieren musst.',
      },
      {
        title: '4. Fehler als eigene Arbeitsmenge behandeln',
        detail: 'Fehler gehoeren in einen separaten Nacharbeitsprozess.',
        action: 'Nutze die Fehlerzusammenfassung, um problematische Dateien gezielt spaeter ueber Set Import oder eine bereinigte neue Queue zu behandeln.',
        expected: 'Fehler sind sichtbar und gehen nicht zwischen Erfolgen unter.',
        warning: 'Fehlgeschlagene Items in der Queue stehen zu lassen erzeugt leicht Scheinsicherheit.',
      },
      {
        title: '5. Erfolgreiche Items aufraeumen',
        detail: 'Eine leere oder bereinigte Queue ist Teil eines sauberen Abschlusses.',
        action: 'Klicke `Fertige loeschen`, wenn du nur noch offene oder problematische Eintraege sehen willst.',
        expected: 'Die Queue zeigt nur noch relevanten Restbestand.',
        warning: 'Lass fertige Erfolge nicht endlos stehen, wenn du aus der Queue spaeter noch Entscheidungen ableitest.',
      },
    ],
    practiceTasks: [
      'Lege einige Testdateien in die Dropzone und lies danach Pending-, Success- und Error-Status ab.',
      'Starte einen kurzen Lauf und beobachte, wie sich der Gesamtfortschritt verhaelt.',
      'Nutze die Queue als Nacharbeitsliste und ueberlege, welche Items du lieber einzeln im Set Import behandeln wuerdest.',
    ],
    commonMistakes: [
      'Batch als Ersatz fuer redaktionelle Einzelkontrolle zu verwenden.',
      'Die Queue ungeprueft zu starten.',
      'Fehler aus dem Batch nicht sichtbar nachzuhalten.',
    ],
    tips: [
      'Batch Import ist stark fuer Menge, schwach fuer Feinschliff.',
      'Bei grossen Chargen lohnt sich ein paralleler Blick in den System Monitor.',
    ],
    successChecks: [
      'Die Queue enthaelt nur beabsichtigte Dateien.',
      'Der Fortschrittsbalken und die Statuswechsel sind nachvollziehbar.',
      'Fehler wurden separat identifiziert.',
      'Fertige Items wurden aufgeraeumt oder bewusst belassen.',
    ],
    relatedTabs: [
      'Set Import fuer problematische Einzelfaelle.',
      'System Monitor fuer Lastsituationen.',
      'Overview fuer anschliessende Plausibilitaetskontrolle.',
    ],
  },
  {
    id: 'flightdeck',
    tabId: 'flightdeck',
    title: 'Flight Deck',
    shortTitle: 'Automation steuern',
    objective: 'Flight Deck ist die kompakte Schaltzentrale fuer Workspace, Publish-Automation, Git-Strategie und zentrale Betriebs-Toggles.',
    whenToUse: 'Vor produktiven Publishes, bei Workspace-Wechseln und immer dann, wenn Automatisierungsverhalten angepasst werden muss.',
    beforeYouStart: [
      'Klaere, ob du nur lokal testen oder wirklich produktiv publizieren willst.',
      'Wenn du neue Automatisierungen aktivierst, plane einen kontrollierten Testlauf ein.',
      'Pruefe in Overview, auf welchem Branch du arbeitest.',
    ],
    keyFunctions: [
      'Verbindet oder wechselt den Workspace.',
      'Pflegt R2 Prefix, Cover Output Dir, Build Command und Deploy Command.',
      'Steuert Commit Template, Publish Position und Default Vinyl Color.',
      'Schaltet Safe Mode, Upload, Cover-Extraktion, Stats-Seeding, Build, Deploy, Commit und Push.',
      'Speichert die Basis-Konfiguration fuer produktive Publish-Laeufe.',
    ],
    controls: [
      {
        name: 'Workspace',
        area: 'Toolbar',
        purpose: 'Waehlt den aktiven AIRDOX-Workspace aus.',
        howToUse: 'Nutze die Schaltflaeche bei neuem Arbeitsplatz oder wenn der aktuelle Root nicht stimmt.',
      },
      {
        name: 'Settings speichern',
        area: 'Toolbar',
        purpose: 'Persistiert die aktuellen Flight-Deck-Werte.',
        howToUse: 'Speichere nach jeder bewussten Aenderung. Nicht nach jedem Tippen reflexhaft, sondern nach Review.',
      },
      {
        name: 'Workspace Root',
        area: 'Workspace-Karte',
        purpose: 'Zeigt den aktiven Root read-only an.',
        howToUse: 'Pruefe hier, ob du wirklich im gewuenschten Projekt arbeitest.',
      },
      {
        name: 'R2 Prefix / Cover Output Dir',
        area: 'Workspace-Karte',
        purpose: 'Steuern Speicherort fuer Artefakte und Objektpfade.',
        howToUse: 'Passe nur an, wenn du die Dateistruktur oder Bucket-Logik bewusst aenderst.',
      },
      {
        name: 'Build Command / Deploy Command',
        area: 'Workspace-Karte',
        purpose: 'Legen fest, was technisch nach einem Publish laeuft.',
        howToUse: 'Nutze echte, getestete Kommandos. Dieses Feld ist kein Experimentierplatz.',
      },
      {
        name: 'Commit Template / Publish Position / Default Vinyl Color',
        area: 'Workspace-Karte',
        purpose: 'Steuern Git-Lesbarkeit, Manifest-Reihenfolge und Standarddarstellung.',
        howToUse: 'Halte das Commit Template stabil und waehle Publish Position bewusst passend zum Frontend-Verhalten.',
      },
      {
        name: 'Automation Toggles',
        area: 'Rechte Karte',
        purpose: 'Steuern, welche Schritte automatisch nach Publish laufen.',
        howToUse: 'Aktiviere Toggles nur, wenn der jeweilige Folgeprozess bewusst Teil deines produktiven Ablaufs ist.',
      },
    ],
    walkthrough: [
      {
        title: '1. Workspace bewusst verbinden',
        detail: 'Ohne korrekten Workspace laufen Import, Publish und State-Laden ins Leere oder in den falschen Kontext.',
        action: 'Klicke `Workspace`, waehle das echte Projektverzeichnis und kontrolliere danach das read-only Root-Feld.',
        expected: 'Flight Deck zeigt den korrekten Workspace Root an.',
        warning: 'Ein falscher Workspace ist einer der teuersten Fehler, weil fast jeder Folgeschritt dann formal erfolgreich wirken kann.',
      },
      {
        title: '2. Pfad- und Kommando-Felder pruefen',
        detail: 'Diese Felder bestimmen, wohin Artefakte gehen und was beim Publish ausgefuehrt wird.',
        action: 'Kontrolliere R2 Prefix, Cover Output Dir, Build Command und Deploy Command gegen deine reale Infrastruktur.',
        expected: 'Die technische Kette passt zu Projektstruktur und Deployment-Pfad.',
        warning: 'Tippfehler in Build oder Deploy Command zeigen sich oft erst tief im Publish-Lauf.',
      },
      {
        title: '3. Git- und Darstellungswerte setzen',
        detail: 'Commit-Template und Publish-Reihenfolge wirken auf Nachvollziehbarkeit und Frontend-Ausspielung.',
        action: 'Lege Commit Template, Publish Position und Default Vinyl Color so fest, dass sie zu deinem Betriebsmodus passen.',
        expected: 'Releases bleiben im Verlauf lesbar und im Frontend konsistent.',
        warning: 'Ein schlechtes Commit Template ist selten kritisch beim ersten Lauf, aber langfristig teuer.',
      },
      {
        title: '4. Automation Toggles bewusst entscheiden',
        detail: 'Jeder Toggle erweitert den automatischen Radius eines Publishes.',
        action: 'Pruefe Safe Mode, Upload Audio, Cover-Extraktion, Stats-Seeding, Auto Build, Auto Deploy, Auto Commit und Auto Push einzeln.',
        expected: 'Der Publish tut spaeter genau das, was du technisch und organisatorisch willst.',
        warning: 'Mehr Automation ist nicht automatisch besser. Sie braucht sauberere Eingangsdaten und mehr Vertrauen in die Kette.',
      },
      {
        title: '5. Speichern und im Kontext pruefen',
        detail: 'Erst das Speichern macht die Konfiguration dauerhaft wirksam.',
        action: 'Klicke `Settings speichern` und pruefe danach bei Gelegenheit in Overview oder beim naechsten Testlauf, ob alles wie erwartet greift.',
        expected: 'Die neue Betriebslogik ist aktiv und nachvollziehbar.',
        warning: 'Ungespeicherte Aenderungen erzeugen die gefaehrlichste Art von Fehler: vermeintlich gemachte Konfiguration.',
      },
    ],
    practiceTasks: [
      'Lies den aktuellen Workspace Root ab und gleiche ihn mit dem erwarteten Projekt ab.',
      'Pruefe, welche Toggles aktuell aktiv sind und was das fuer einen Publish konkret bedeutet.',
      'Kontrolliere, ob Build- und Deploy-Command zur aktuellen Umgebung passen.',
    ],
    commonMistakes: [
      'Workspace Root nicht gegenpruefen.',
      'Auto Push zu aktivieren, obwohl Branch oder Remote nicht sauber geklaert sind.',
      'Safe Mode auszuschalten, obwohl noch unklare Quelldaten im Spiel sind.',
    ],
    tips: [
      'Halte Safe Mode standardmaessig aktiv.',
      'Teste geaenderte Automation lieber kontrolliert als auf dem naechsten wichtigen Release.',
    ],
    successChecks: [
      'Workspace Root ist korrekt.',
      'Build- und Deploy-Kommandos sind plausibel.',
      'Die aktivierten Toggles entsprechen dem gewuenschten Publish-Ablauf.',
      'Aenderungen wurden gespeichert.',
    ],
    relatedTabs: [
      'Set Import fuer den eigentlichen Publish.',
      'Advanced Settings fuer tiefere Feinsteuerung.',
      'Overview fuer Kontrolle vor und nach dem Lauf.',
    ],
  },
  {
    id: 'settings',
    tabId: 'settings',
    title: 'Advanced Settings',
    shortTitle: 'Feinsteuerung',
    objective: 'Advanced Settings ist das feinere Konfigurationszentrum fuer Workspace, Build, Deploy, Git, Live-Updates und Darstellung.',
    whenToUse: 'Wenn du nicht nur einzelne Toggles setzen, sondern die Gesamtstrategie fuer Betrieb und Synchronisierung justieren willst.',
    beforeYouStart: [
      'Arbeite gruppenweise statt chaotisch ueber alle Felder.',
      'Aendere moeglichst nur eine Strategie gleichzeitig, z. B. erst Deploy, dann Live Updates.',
      'Erwarte nicht, dass `Zuruecksetzen` auf Fabrikzustand geht. Es holt den zuletzt geladenen Zustand zurueck.',
    ],
    keyFunctions: [
      'Gruppiert Einstellungen in Workspace-Grundlagen, Build & Deploy, Git-Workflow, Core Automation, Live-Update-System und Anzeigeoptionen.',
      'Zeigt Speicherrueckmeldungen mit Statusindikatoren.',
      'Erlaubt Ruecksetzen auf den geladenen Zustand.',
      'Pflegt Deploy Strategy, Branch-Strategie, Auto-Merge sowie Live-Update-Intervalle und Theme.',
    ],
    controls: [
      {
        name: 'Speichern',
        area: 'Toolbar',
        purpose: 'Speichert die geaenderten Advanced Settings.',
        howToUse: 'Der Button ist nur bei erkannten Aenderungen aktiv. Nutze ihn nach einem bewussten Gruppen-Review.',
      },
      {
        name: 'Zuruecksetzen',
        area: 'Toolbar',
        purpose: 'Verwirft lokale Aenderungen und laedt den aktuellen gespeicherten Zustand erneut.',
        howToUse: 'Sinnvoll, wenn du dich in einer Einstellungsgruppe verlaufen hast oder wieder auf den geladenen Stand zurueck willst.',
      },
      {
        name: 'Save Status',
        area: 'Toolbar',
        purpose: 'Zeigt `pending`, `success` oder `error` beim Speichern.',
        howToUse: 'Verlasse den Tab nicht blind nach dem Klick, sondern lies die Rueckmeldung.',
      },
      {
        name: 'Workspace-Grundlagen',
        area: 'Linke Spalte',
        purpose: 'Pflegt Basiswerte wie Prefix und Output-Ordner.',
        howToUse: 'Nur aendern, wenn du die Projektstruktur oder Artefaktpfade wirklich anpassen musst.',
      },
      {
        name: 'Build & Deploy',
        area: 'Linke Spalte',
        purpose: 'Steuert Build- und Deploy-Befehle sowie Deploy-Strategie.',
        howToUse: 'Aendere die Strategie nur mit klarem Betriebsmodell: automatic, manual oder staged.',
      },
      {
        name: 'Git-Workflow',
        area: 'Linke Spalte',
        purpose: 'Steuert Commit-Vorlage, Ziel-Branch-Strategie und Auto-Merge.',
        howToUse: 'Besonders sensibel in Teams oder bei mehreren gleichzeitigen Publishes.',
      },
      {
        name: 'Core Automation',
        area: 'Rechte Spalte',
        purpose: 'Spiegelt und erweitert die wichtigsten Publish-Toggles.',
        howToUse: 'Nutze diesen Block fuer bewusste Feinabstimmung, nicht fuer hektische Schnellschuesse.',
      },
      {
        name: 'Live-Update-System',
        area: 'Rechte Spalte',
        purpose: 'Steuert Polling, Alerts und Echtzeitverhalten.',
        howToUse: 'Passe Intervalle und Warnungen an die Arbeitslast an. Zu schnelle Polling-Zyklen kosten Ressourcen.',
      },
      {
        name: 'Anzeigeoptionen',
        area: 'Rechte Spalte',
        purpose: 'Pflegt Theme, Publish Position und Standardfarbe.',
        howToUse: 'UI-Einstellungen sind nachrangig, aber fuer klare Betriebsumgebungen dennoch relevant.',
      },
    ],
    walkthrough: [
      {
        title: '1. Gruppenweise arbeiten',
        detail: 'Dieser Tab ist absichtlich granular. Unstrukturierte Aenderungen fuehren schnell zu unklaren Nebenwirkungen.',
        action: 'Nimm dir immer nur eine Einstellungsgruppe vor und schliesse sie gedanklich ab, bevor du in die naechste gehst.',
        expected: 'Du kannst spaeter nachvollziehen, welche Aenderung welche Wirkung hatte.',
        warning: 'Mehrere Strategiewechsel gleichzeitig erschweren jede Fehlersuche.',
      },
      {
        title: '2. Workspace und Deploy-Basis abgleichen',
        detail: 'Diese Basis bestimmt, wohin publiziert wird und wie Artefakte verarbeitet werden.',
        action: 'Pruefe Prefix, Output-Verzeichnis, Build Command, Deploy Command und Deploy Strategy gegen die reale Umgebung.',
        expected: 'Die technische Grundlage passt zu deinem Zielsystem.',
        warning: 'Falsche Deploy-Strategien sind organisatorische Fehler, nicht nur technische.',
      },
      {
        title: '3. Git-Strategie bewusst setzen',
        detail: 'Commit-Vorlage, Branch-Strategie und Auto-Merge definieren, wie Releases historisch landen.',
        action: 'Waehle die passende Branch-Strategie und entscheide vorsichtig ueber automatischen Merge.',
        expected: 'Der Git-Fluss ist nicht zufaellig, sondern geplant.',
        warning: 'Auto-Merge ist nur dann sinnvoll, wenn Upstream-Prozesse klar sind.',
      },
      {
        title: '4. Core Automation und Live Updates fein abstimmen',
        detail: 'Hier kontrollierst du, wie aktiv und wie aggressiv das Tool arbeitet.',
        action: 'Setze Toggles und Live-Update-Werte so, dass sie zu deinem Betriebsmodus und deiner Hardware passen.',
        expected: 'Das Tool reagiert weder zu traege noch unnötig aggressiv.',
        warning: 'Sehr schnelle Live-Updates koennen lokale Last und visuelle Unruhe erhoehen.',
      },
      {
        title: '5. Speichern und Rueckmeldung abwarten',
        detail: 'Die Rueckmeldung ist Teil des Workflows, kein kosmetisches Detail.',
        action: 'Klicke `Speichern` und beobachte den Status bis Erfolg oder Fehler sichtbar ist.',
        expected: 'Du weisst, ob die Aenderung wirklich persistiert wurde.',
        warning: 'Ein Tab-Wechsel direkt nach dem Klick fuehrt leicht zu Irrtum ueber den echten Zustand.',
      },
    ],
    practiceTasks: [
      'Pruefe, welche Deploy Strategy aktuell gesetzt ist und ob sie zu deinem Ablauf passt.',
      'Lies das Live-Update-Intervall ab und entscheide, ob es fuer deine aktuelle Arbeitslast sinnvoll ist.',
      'Simuliere eine Aenderung gedanklich gruppenweise: erst Build & Deploy, dann separat Git-Workflow.',
    ],
    commonMistakes: [
      'Mehrere Strategiefelder gleichzeitig umzustellen.',
      'Zuruecksetzen mit Werksreset zu verwechseln.',
      'Save-Status nicht abzuwarten.',
    ],
    tips: [
      'Live-Update-Intervalle unter 1s sind nur fuer enge Monitoring-Szenarien sinnvoll.',
      'Wenn du Flight Deck fuer den Schnellzugriff nutzt, ist Advanced Settings der Ort fuer die ruhige Feinjustierung.',
    ],
    successChecks: [
      'Die bearbeiteten Gruppen sind bewusst gewaehlt.',
      'Save-Status zeigt Erfolg oder einen klaren Fehler.',
      'Kein Feld blieb unbeabsichtigt in einem Zwischenzustand.',
    ],
    relatedTabs: [
      'Flight Deck fuer die kompakte Betriebsansicht.',
      'System Monitor, wenn Live Updates Last erzeugen.',
      'Set Import fuer den praktischen Gegencheck bei Publish-nahem Verhalten.',
    ],
  },
  {
    id: 'monitor',
    tabId: 'monitor',
    title: 'System Monitor',
    shortTitle: 'Laufzeit absichern',
    objective: 'System Monitor zeigt Last, Engpaesse und Prozesse der lokalen Laufzeitumgebung und hilft bei Performance- oder Stabilitaetsfragen.',
    whenToUse: 'Bei langsamen Imports, auffaelligen Builds, Performanceproblemen, hoher Last und vor groesseren Automationslaeufen.',
    beforeYouStart: [
      'Nutze den Tab nicht fuer fachliche Inhaltsfragen, sondern fuer technische Ursachenanalyse.',
      'Plane nach Admin-Aktionen immer einen erneuten Refresh ein.',
      'Betrachte Lastwerte nie isoliert, sondern zusammen mit Warnungen und Prozessbild.',
    ],
    keyFunctions: [
      'Zeigt RAM-, CPU- und Disk-Auslastung mit Health-Signal.',
      'Zeigt DB-Connections bezogen auf aktive Prozesse.',
      'Listet Warnungen bei Lastproblemen.',
      'Zeigt Memory-Nutzung, Top Prozesse und einen Prozessueberblick.',
      'Bietet `Cache loeschen`, `Optimieren` und `Aktualisieren`.',
    ],
    controls: [
      {
        name: 'Aktualisieren',
        area: 'Toolbar',
        purpose: 'Laedt die aktuellen Systemwerte neu.',
        howToUse: 'Pflichtschritt vor jeder Interpretation und nach jeder Admin-Aktion.',
      },
      {
        name: 'Cache loeschen',
        area: 'Toolbar',
        purpose: 'Fuehrt Cache-Bereinigung aus.',
        howToUse: 'Nur bei echter Cache-Problemlage oder als gezielte Entlastungsmassnahme nutzen.',
      },
      {
        name: 'Optimieren',
        area: 'Toolbar',
        purpose: 'Stoesst Optimierungslogik an.',
        howToUse: 'Fuer gezielte Entlastung oder Wiederherstellung, nicht als Dauerknopf.',
      },
      {
        name: 'RAM / CPU / Disk / DB Connection',
        area: 'Metrik-Bereich',
        purpose: 'Geben die schnelle Gesamtlage wieder.',
        howToUse: 'Lies zuerst diese vier Werte gemeinsam, bevor du in Details gehst.',
      },
      {
        name: 'Warnungen',
        area: 'Mittelbereich',
        purpose: 'Buesndeln kritische oder warnende Systemhinweise.',
        howToUse: 'Gehe Warnungen aktiv durch. Sie sind hier das priorisierte Signal.',
      },
      {
        name: 'Memory-Nutzung',
        area: 'Linke Detailkarte',
        purpose: 'Zeigt Belegung und Verfuegbarkeit im Detail.',
        howToUse: 'Besonders wichtig waehrend Batch-Import, Build oder anderen speicherintensiven Vorgangen.',
      },
      {
        name: 'Top Prozesse / Alle Prozesse',
        area: 'Rechte Karte und Tabelle',
        purpose: 'Zeigen, welche Prozesse Last oder Speicher verbrauchen.',
        howToUse: 'Suche nach unerwarteten Prozessen oder nach ungewoehnlich hohem Verbrauch der erwarteten Prozesse.',
      },
    ],
    walkthrough: [
      {
        title: '1. Schnelllage oben lesen',
        detail: 'Die vier Metrik-Karten sind dein erster Gesundheitscheck.',
        action: 'Pruefe RAM, CPU, Disk und DB Connection gemeinsam und beachte Farben sowie Prozentwerte.',
        expected: 'Du erkennst sofort, ob du im gesunden, warnenden oder kritischen Bereich bist.',
        warning: 'Ein einzelner hoher Wert ist noch kein Urteil. Erst Kombination und Dauer machen ein Problem daraus.',
      },
      {
        title: '2. Warnungen priorisieren',
        detail: 'Warnungen sind die fokussierte Zusammenfassung der eigentlichen Probleme.',
        action: 'Lies Titel und Beschreibung jeder Warnung und entscheide, ob du nur beobachtest oder aktiv eingreifen musst.',
        expected: 'Du arbeitest zuerst am wichtigsten technischen Signal.',
        warning: 'Warnungen zu ignorieren und direkt in Prozesslisten zu springen kostet Zeit.',
      },
      {
        title: '3. Speicherlage im Detail pruefen',
        detail: 'Die Memory-Karte zeigt, ob ein Import oder Build lokal an Grenzen stoesst.',
        action: 'Vergleiche Prozentbelegung, MB verwendet und MB verfuegbar.',
        expected: 'Du kannst einschaetzen, ob Lastspitzen nur kurzfristig oder bereits problematisch sind.',
        warning: 'Hohe RAM-Nutzung ohne verfuegbare Reserve ist deutlich relevanter als hohe RAM-Nutzung allein.',
      },
      {
        title: '4. Prozesse vergleichen',
        detail: 'Top Prozesse zeigen, wo Last konkret anfaellt.',
        action: 'Suche in `Top Prozesse` und `Alle Prozesse` nach erwarteten und unerwarteten Lasttreibern.',
        expected: 'Du weisst, ob das Tool selbst, ein Build oder ein Fremdprozess den Druck erzeugt.',
        warning: 'Nur auf Prozessnamen zu schauen reicht nicht. Der Speicher- und Statuskontext ist wichtig.',
      },
      {
        title: '5. Admin-Aktionen gezielt und messbar einsetzen',
        detail: 'Aktionen im Monitor sind Eingriffe, keine Navigation.',
        action: 'Fuehre `Cache loeschen` oder `Optimieren` nur mit begruendetem Ziel aus und druecke danach `Aktualisieren`.',
        expected: 'Du kannst die Wirkung des Eingriffs direkt am aktualisierten Zustand sehen.',
        warning: 'Ohne Nachmessung weisst du nicht, ob der Eingriff geholfen hat.',
      },
    ],
    practiceTasks: [
      'Lies RAM-, CPU- und Disk-Wert gemeinsam und entscheide, ob gerade ein technischer Engpass sichtbar ist.',
      'Pruefe, welche Prozesse in deiner aktuellen Sitzung oben stehen und ob sie erwartbar sind.',
      'Simuliere gedanklich einen Batch-Import und benenne, welche drei Bereiche du parallel beobachten wuerdest.',
    ],
    commonMistakes: [
      'Den Monitor fuer fachliche Reporting-Fragen zu benutzen.',
      'Admin-Aktionen ohne erneuten Refresh auszufuehren.',
      'Nur auf Prozentwerte und nicht auf Warnungen oder Prozessliste zu achten.',
    ],
    tips: [
      'System Monitor ist besonders wertvoll parallel zu Batch-Importen oder grossen Publishes.',
      '`DB Connection` ist hier eher ein grober Technik-Hinweis als eine tiefgehende Datenbankdiagnose.',
    ],
    successChecks: [
      'Die aktuelle Lastlage ist verstanden.',
      'Warnungen wurden gelesen und eingeordnet.',
      'Nach Aktionen wurde erneut aktualisiert.',
      'Der mutmassliche Lasttreiber ist identifiziert oder ausgeschlossen.',
    ],
    relatedTabs: [
      'Batch Import fuer grosse Dateimengen.',
      'Analytics oder Data Explorer, wenn Queries traege wirken.',
      'Advanced Settings fuer Live-Update- und Polling-Anpassungen.',
    ],
  },
  {
    id: 'tutorial',
    tabId: 'tutorial',
    title: 'Tutorial',
    shortTitle: 'Handbuch im Tool',
    objective: 'Der Tutorial-Tab ist das dauerhafte Nachschlagewerk im Tool: Checkliste, gefuehrte Touren, Szenarien und tabweises Handbuch an einem Ort.',
    whenToUse: 'Beim ersten Einstieg, beim Onboarding neuer Nutzer, vor unbekannten Arbeitsablaeufen und als schneller Rueckgriff waehrend des Betriebs.',
    beforeYouStart: [
      'Nutze zuerst die Tour fuer den roten Faden, danach die Abschnittsseiten fuer Details.',
      'Wiederkehrende Aufgaben lernst du am schnellsten ueber die Szenario-Touren, nicht ueber reines Durchlesen.',
    ],
    keyFunctions: [
      'Zeigt eine Besuchs-Checkliste ueber die wichtigsten Betriebs-Tabs.',
      'Bietet gefuehrte Touren fuer Gesamteinstieg, Datenbank-Audit, Release und technische Analyse.',
      'Dokumentiert jeden Tab mit Zweck, Controls, Schritten, Praxisaufgaben und Fehlerbildern.',
      'Erlaubt direkten Sprung in Tabs oder gefuehrte Schritte.',
    ],
    controls: [
      {
        name: 'Interaktive Tour starten',
        area: 'Hero',
        purpose: 'Startet die komplette Einstiegstour.',
        howToUse: 'Ideal beim ersten Einstieg oder wenn du den roten Faden des Tools neu verstehen willst.',
      },
      {
        name: 'Schnellstart-Checkliste',
        area: 'Linke Spalte',
        purpose: 'Zeigt, welche Kern-Tabs bereits besucht wurden.',
        howToUse: 'Nutze `Oeffnen`, um fehlende Bereiche direkt anzuspringen.',
      },
      {
        name: 'Gefuehrte Touren',
        area: 'Rechte Spalte',
        purpose: 'Startet workflow-orientierte Touren statt reiner Feature-Aufzaehlung.',
        howToUse: 'Waehle die Tour passend zu deinem Ziel, z. B. Datenbank-Audit oder Set-Publish.',
      },
      {
        name: 'Tab oeffnen / Gefuehrte Schritte',
        area: 'Je Abschnitt',
        purpose: 'Erlaubt direkten Sprung in den Tab oder die gefuehrte Tour ab diesem Kontext.',
        howToUse: 'Perfekt, wenn du waehrend einer Aufgabe gezielt in einen Unterbereich springen willst.',
      },
    ],
    walkthrough: [
      {
        title: '1. Tour statt Scroll-Marathon starten',
        detail: 'Der schnellste Einstieg ist die gefuehrte Tour, nicht das Volllesen aller Texte.',
        action: 'Nutze zuerst `Interaktive Tour starten` oder eine konkrete Szenario-Tour.',
        expected: 'Du bekommst eine sinnvolle Reihenfolge statt einer ueberladenen Feature-Wand.',
        warning: 'Nur zu lesen, ohne einmal durch die reale UI zu gehen, bleibt oft abstrakt.',
      },
      {
        title: '2. Checkliste als Fortschrittsbild nutzen',
        detail: 'Die Checkliste zeigt dir, welche Betriebsbereiche du bereits gesehen hast.',
        action: 'Oeffne offene Bereiche direkt ueber die Buttons und arbeite dich durch die wichtigsten Tabs.',
        expected: 'Du siehst schnell, welche Wissensluecken noch offen sind.',
        warning: 'Besuchter Tab heisst noch nicht verstandener Tab. Nutze die Detailabschnitte dazu.',
      },
      {
        title: '3. Szenario passend zum Ziel waehlen',
        detail: 'Gute Onboarding-Hilfe startet beim Arbeitsziel, nicht bei der Komponentenliste.',
        action: 'Waehle eine Tour wie `Szenario 2: Auswertung der Datenbank`, wenn du genau dieses Ergebnis willst.',
        expected: 'Du lernst das Tool ueber echte Aufgaben und Reihenfolgen.',
        warning: 'Die Volltour ist nicht immer die beste Wahl, wenn du nur eine konkrete Betriebsfrage beantworten willst.',
      },
    ],
    practiceTasks: [
      'Starte die Volltour und vergleiche danach die Checkliste mit deinem Eindruck.',
      'Waehle gezielt `Szenario 2: Auswertung der Datenbank` und pruefe, ob die Reihenfolge zu deiner Frage passt.',
      'Oeffne einen Tab erst direkt, dann ueber `Gefuehrte Schritte`, und vergleiche den Unterschied im Einstieg.',
    ],
    commonMistakes: [
      'Das Tutorial nur als statische Doku zu sehen und die Touren nicht zu nutzen.',
      'Mit der Volltour zu arbeiten, obwohl eigentlich nur ein einzelnes Szenario gebraucht wird.',
    ],
    tips: [
      'Nutze das Tutorial als Betriebsinstrument, nicht nur als Einsteigerhilfe.',
      'Die gefuehrten Touren sind absichtlich task-orientiert und koennen immer wieder genutzt werden.',
    ],
    successChecks: [
      'Du kennst mindestens eine Tour, die zu deinem aktuellen Ziel passt.',
      'Du kannst aus der Checkliste in offene Bereiche springen.',
      'Du weisst, dass der Tutorial-Tab das dauerhafte Handbuch im Tool ist.',
    ],
    relatedTabs: [
      'Alle operativen Tabs sind von hier direkt erreichbar.',
    ],
  },
];

const fullTourSteps = [
  {
    id: 'welcome',
    title: 'Willkommen im Flight Deck',
    tabId: 'tutorial',
    checklistId: 'tutorial',
    description: 'Diese Tour fuehrt dich nicht als Feature-Tour durch jedes Element, sondern entlang der echten Arbeitslogik des Tools.',
    actions: [
      'Merke dir die Grundregel: erst Zustand pruefen, dann analysieren, dann aendern oder publizieren.',
      'Nutze danach je nach Aufgabe eine Szenario-Tour oder springe direkt in einen Detailabschnitt.',
    ],
    expectedResults: [
      'Du verstehst, dass der Workflow wichtiger ist als eine lineare UI-Beschreibung.',
    ],
  },
  {
    id: 'overview-start',
    title: 'Schritt 1: Overview als Startpunkt',
    tabId: 'overview',
    checklistId: 'overview',
    description: 'Beginne jede produktive Session im Overview und lies dort Workspace, Snapshot und Git-Lage.',
    actions: [
      'Pruefe Workspace-Pill und Branch-Pill im Header.',
      'Lies die vier Metrik-Karten zusammen.',
      'Kontrolliere Top Sets und juengste Analytics-Ereignisse.',
    ],
    expectedResults: [
      'Du kennst den Ausgangszustand des Systems.',
      'Du bemerkst frueh, ob Daten oder Workspace unplausibel wirken.',
    ],
  },
  {
    id: 'analytics-read',
    title: 'Schritt 2: Analytics mit Kontext lesen',
    tabId: 'analytics',
    checklistId: 'analytics',
    description: 'Setze Zeitraum und Filter, bevor du Kennzahlen deutest oder exportierst.',
    actions: [
      'Waehle einen klaren Zeitraum.',
      'Setze Event-Typ, Geraet oder Land nur dann, wenn sie Teil deiner Frage sind.',
      'Lies danach Top Sets, Geo, Device und Tageszeit nacheinander.',
    ],
    expectedResults: [
      'Die Analytics-Zahlen bekommen fachlichen Kontext.',
      'Reports entstehen nicht mehr aus unklaren Filterzustaenden.',
    ],
  },
  {
    id: 'explorer-safe',
    title: 'Schritt 3: Data Explorer sicher nutzen',
    tabId: 'explorer',
    checklistId: 'explorer',
    description: 'Waehle die richtige Tabelle, filtere eng und speichere nur bewusst.',
    actions: [
      'Stelle die passende Tabelle ein.',
      'Begrenze den Suchraum ueber `Filtern...`.',
      'Nutze SQL nur fuer lesende Sonderfragen.',
    ],
    expectedResults: [
      'Du arbeitest mit kleinen, kontrollierten Datenmengen.',
      'Du weisst, welche Tabellen editierbar und welche nur lesend sind.',
    ],
  },
  {
    id: 'import-single',
    title: 'Schritt 4: Set Import fuer Einzelreleases',
    tabId: 'import',
    checklistId: 'import',
    description: 'Importiere Audio, Cover und Tracklist, pruefe den Draft und lies das Publish Log bis zum Ende.',
    actions: [
      'Lade Quelldateien in die Dropzone.',
      'Bearbeite Warnungen und kontrolliere Kernfelder.',
      'Pruefe die Tracklist und starte erst dann den Publish.',
    ],
    expectedResults: [
      'Du kennst den sauberen Einzel-Release-Ablauf.',
      'Du verstehst, warum Publish ohne Nachkontrolle unvollstaendig ist.',
    ],
  },
  {
    id: 'batch-volume',
    title: 'Schritt 5: Batch Import fuer Mengen',
    tabId: 'batch',
    checklistId: 'batch',
    description: 'Nutze Batch nur fuer Volumen und behandle Fehler spaeter gezielt.',
    actions: [
      'Fuelle die Queue mit mehreren Dateien.',
      'Pruefe die Queue vor dem Start.',
      'Beobachte Status, Fortschritt und Fehlerliste.',
    ],
    expectedResults: [
      'Du erkennst den Unterschied zwischen Volumenverarbeitung und Einzelredaktion.',
    ],
  },
  {
    id: 'flightdeck-automation',
    title: 'Schritt 6: Flight Deck fuer Betriebslogik',
    tabId: 'flightdeck',
    checklistId: 'flightdeck',
    description: 'Hier legst du fest, was nach einem Publish technisch automatisch passieren darf.',
    actions: [
      'Pruefe Workspace Root, Build und Deploy Command.',
      'Bewerte Safe Mode und die Automation Toggles.',
      'Speichere nur nach bewusstem Review.',
    ],
    expectedResults: [
      'Du verstehst den Automationsradius des Tools.',
    ],
  },
  {
    id: 'settings-detail',
    title: 'Schritt 7: Advanced Settings fuer Feineinstellungen',
    tabId: 'settings',
    checklistId: 'settings',
    description: 'Arbeite gruppenweise und aendere nicht mehrere Strategien gleichzeitig.',
    actions: [
      'Pruefe eine Einstellungsgruppe nach der anderen.',
      'Kontrolliere Save-Status nach dem Speichern.',
    ],
    expectedResults: [
      'Du kannst tiefe Betriebsparameter ohne Chaos anpassen.',
    ],
  },
  {
    id: 'monitor-health',
    title: 'Schritt 8: System Monitor fuer Technikfragen',
    tabId: 'monitor',
    checklistId: 'monitor',
    description: 'Beobachte Last, Warnungen und Prozesse vor allem bei Batch, Build und Performanceproblemen.',
    actions: [
      'Lies RAM, CPU, Disk und DB Connection gemeinsam.',
      'Arbeite Warnungen priorisiert ab.',
      'Pruefe Prozesse und aktualisiere nach Eingriffen erneut.',
    ],
    expectedResults: [
      'Du kannst fachliche von technischen Problemen sauber trennen.',
    ],
  },
  {
    id: 'tutorial-close',
    title: 'Tour abgeschlossen',
    tabId: 'tutorial',
    checklistId: 'tutorial',
    description: 'Jetzt ist der Tutorial-Tab dein dauerhaftes Handbuch fuer Szenarien, Detailschritte und tabweises Nachschlagen.',
    actions: [
      'Waehle als Naechstes eine Szenario-Tour passend zu deinem aktuellen Ziel.',
      'Nutze die Checkliste, um offene Bereiche gezielt erneut anzuspringen.',
    ],
    expectedResults: [
      'Du hast einen roten Faden fuer das gesamte Tool.',
    ],
  },
];

export const TUTORIAL_TOURS = {
  full: {
    id: 'full',
    title: 'Volltour: Alle Betriebsbereiche verstehen',
    description: 'Die komplette Fuehrung fuer Erstnutzung oder fuer einen sauberen Gesamtueberblick ueber alle zentralen Tabs.',
    estimatedTime: '12-15 Min',
    intent: 'Gesamteinstieg',
    steps: fullTourSteps,
  },
  firstSession: {
    id: 'firstSession',
    title: 'Erste produktive Session',
    description: 'Die empfohlene Reihenfolge, wenn du das Tool neu oeffnest oder einen Arbeitsplatz frisch vorbereitest.',
    estimatedTime: '6-8 Min',
    intent: 'Arbeitsplatz vorbereiten',
    steps: [
      {
        id: 'first-overview',
        title: '1. Overview: Ausgangslage sichern',
        tabId: 'overview',
        checklistId: 'overview',
        description: 'Pruefe, ob Workspace, Manifest und Git in einem belastbaren Zustand sind.',
        actions: [
          'Pruefe Workspace und Branch.',
          'Lies Metrik-Karten und Top Sets.',
          'Notiere fehlende `track_stats`, falls vorhanden.',
        ],
        expectedResults: [
          'Du kennst die Startlage der Session.',
        ],
      },
      {
        id: 'first-flightdeck',
        title: '2. Flight Deck: Betriebsparameter kontrollieren',
        tabId: 'flightdeck',
        checklistId: 'flightdeck',
        description: 'Gleiche Workspace, Befehle und Automation Toggles mit dem heutigen Ziel ab.',
        actions: [
          'Pruefe Workspace Root.',
          'Kontrolliere Build/Deploy-Command und Safe Mode.',
        ],
        expectedResults: [
          'Die Publish-Kette ist auf den heutigen Lauf eingestellt.',
        ],
      },
      {
        id: 'first-settings',
        title: '3. Advanced Settings: Feineinstellungen pruefen',
        tabId: 'settings',
        checklistId: 'settings',
        description: 'Pruefe tiefe Einstellungen nur dort, wo sie fuer diese Session relevant sind.',
        actions: [
          'Kontrolliere Deploy Strategy und Live-Update-Verhalten.',
          'Speichere nur bei echten Aenderungen.',
        ],
        expectedResults: [
          'Keine versteckten Konfigurationsueberraschungen im spaeteren Ablauf.',
        ],
      },
      {
        id: 'first-close',
        title: '4. Zurueck in Overview: Start freigeben',
        tabId: 'overview',
        checklistId: 'overview',
        description: 'Zum Abschluss noch einmal den Zustand lesen, bevor du fachlich oder produktiv weiterarbeitest.',
        actions: [
          'Fuehre einen Refresh aus.',
          'Pruefe erneut Branch, Status und Snapshot.',
        ],
        expectedResults: [
          'Die Session ist sauber vorbereitet.',
        ],
      },
    ],
  },
  databaseAudit: {
    id: 'databaseAudit',
    title: 'Szenario 2: Auswertung der Datenbank nach verschiedenen Kriterien',
    description: 'Die detaillierte Arbeitsfuehrung fuer die Frage, welche Sets performen, welche Nutzung zuletzt passiert ist und welche Rohdaten hinter den Kennzahlen stehen.',
    estimatedTime: '10-14 Min',
    intent: 'Reporting und Plausibilisierung',
    steps: [
      {
        id: 'audit-overview',
        title: '1. Overview: Ausgangslage pruefen',
        tabId: 'overview',
        checklistId: 'overview',
        description: 'Vor jeder fachlichen Auswertung muss klar sein, ob aktuelle Daten ueberhaupt geladen sind.',
        actions: [
          'Pruefe Workspace, Branch und ob der Workspace wirklich geladen ist.',
          'Lies `Sets im Manifest`, `Analytics Events`, `VIP User` und `Sessions`.',
          'Schaue auf `Top Sets` und `Recent Analytics`.',
        ],
        expectedResults: [
          'Du weisst, ob die Datenbasis fuer eine Analyse aktuell und plausibel ist.',
        ],
        warning: 'Wenn `Recent Analytics` leer ist oder die Karten unplausibel wirken, ist jede weitere Auswertung mit Vorsicht zu behandeln.',
      },
      {
        id: 'audit-analytics-range',
        title: '2. Analytics: Zeitraum und Kernfilter setzen',
        tabId: 'analytics',
        checklistId: 'analytics',
        description: 'Die saubere fachliche Auswertung beginnt mit Zeitraum, Event-Typ, Geraet und Land.',
        actions: [
          'Setze `Von` und `Bis`, z. B. letzte 7 Tage oder letzter Monat.',
          'Waehle Event-Typ, falls du nicht auf `Alle` arbeiten willst.',
          'Pruefe optional Geraet und Land fuer eine fokussierte Auswertung.',
        ],
        expectedResults: [
          'Du hast den fachlichen Auswertungskontext sauber gesetzt.',
        ],
      },
      {
        id: 'audit-analytics-read',
        title: '3. Analytics: Kennzahlen und Muster lesen',
        tabId: 'analytics',
        checklistId: 'analytics',
        description: 'Jetzt liest du die aktuelle Leistung nach Reichweite, Nutzung und Resonanz.',
        actions: [
          'Vergleiche `Gesamtaufrufe`, `Plays`, `Likes` und `Engagement Rate`.',
          'Lies `Top Sets` im gesetzten Filterkontext.',
          'Pruefe Geo-Verteilung, Geraete-Breakdown und Tageszeit-Verteilung.',
        ],
        expectedResults: [
          'Du kannst sagen, welche Sets fuehren und welche Laender, Geraete oder Uhrzeiten relevant sind.',
        ],
        warning: 'Erst interpretieren, dann exportieren. Nicht andersherum.',
      },
      {
        id: 'audit-explorer-track-stats',
        title: '4. Explorer: `track_stats` fuer Set-Leistung pruefen',
        tabId: 'explorer',
        checklistId: 'explorer',
        description: 'Wenn Analytics auffaellig ist, gehst du auf die Tabellensicht fuer Set-Performance.',
        actions: [
          'Stelle `track_stats` ein.',
          'Filtere nach relevanter Set-ID oder einer kleinen Vergleichsgruppe.',
          'Pruefe `plays`, `likes`, `dislikes` und `last_played_at`.',
        ],
        expectedResults: [
          'Du kannst die Aggregationssicht von Analytics mit den gespeicherten Set-Stats gegentesten.',
        ],
      },
      {
        id: 'audit-explorer-logs',
        title: '5. Explorer: `analytics_logs` fuer Rohereignisse pruefen',
        tabId: 'explorer',
        checklistId: 'explorer',
        description: 'Hier kontrollierst du, ob das Eventbild die Analytics-Interpretation wirklich traegt.',
        actions: [
          'Wechsle auf `analytics_logs`.',
          'Filtere nach Event-Typ, Item-ID, Land, Geraet oder Browser.',
          'Pruefe, ob juengste Events und Muster zum Analytics-Bild passen.',
        ],
        expectedResults: [
          'Du hast die Rohdatenkontrolle fuer auffaellige Sets oder Regionen durchgefuehrt.',
        ],
      },
      {
        id: 'audit-explorer-admin',
        title: '6. Explorer: `subscribers`, `users` und `sessions` bei Bedarf einbeziehen',
        tabId: 'explorer',
        checklistId: 'explorer',
        description: 'Nicht jede Analyse braucht diese Tabellen, aber bei Reporting oder Betriebskontrolle koennen sie relevant sein.',
        actions: [
          'Pruefe `subscribers`, wenn du Status oder Pflegezustand bewerten willst.',
          'Pruefe `users`, wenn VIP- oder Admin-Zugaenge Teil der Systemkontrolle sind.',
          'Pruefe `sessions`, wenn du aktive oder verdaechtige Sitzungen bewerten willst.',
        ],
        expectedResults: [
          'Du weisst, ob dein Audit nur Nutzungsdaten oder auch Admin-Daten umfassen muss.',
        ],
      },
      {
        id: 'audit-sql-export',
        title: '7. Explorer: Read-only SQL und Export sauber abschliessen',
        tabId: 'explorer',
        checklistId: 'explorer',
        description: 'Wenn UI-Filter nicht reichen, beantwortest du Sonderfragen lesend und exportierst erst am Ende.',
        actions: [
          'Fuehre eine lesende SQL-Abfrage fuer Ranking, Like-Quote oder neueste Events aus.',
          'Pruefe `rowCount` und JSON-Ergebnis.',
          'Exportiere CSV oder JSON erst nach finaler Tabellen- und Filterwahl.',
        ],
        expectedResults: [
          'Deine Auswertung ist dokumentierbar und exportierbar.',
        ],
      },
      {
        id: 'audit-monitor',
        title: '8. System Monitor nur bei Performance-Fragen nutzen',
        tabId: 'monitor',
        checklistId: 'monitor',
        description: 'Dieser Schritt ist optional, aber wichtig, wenn Queries oder Explorer auffaellig traege werden.',
        actions: [
          'Pruefe RAM, CPU, Disk und Top Prozesse.',
          'Aktualisiere nach Bedarf erneut.',
        ],
        expectedResults: [
          'Du kannst technische Ursachen von fachlichen Datenfragen trennen.',
        ],
      },
      {
        id: 'audit-finish',
        title: '9. Analyse sauber abschliessen',
        tabId: 'tutorial',
        checklistId: 'tutorial',
        description: 'Das Szenario ist erst abgeschlossen, wenn Zeitraum, Filter, Gewinner-Sets und Rohdatenbezug klar sind.',
        actions: [
          'Beantworte fuer dich: Welcher Zeitraum? Welche Filter? Welche Sets fuehren? Stimmen Rohdaten und Analytics ueberein?',
          'Halte fest, ob exportiert oder dokumentiert wurde.',
        ],
        expectedResults: [
          'Die Auswertung ist nicht nur angeschaut, sondern fachlich abgeschlossen.',
        ],
      },
    ],
  },
  singleRelease: {
    id: 'singleRelease',
    title: 'Szenario: Ein neues Set sauber veroeffentlichen',
    description: 'Der End-to-End-Ablauf fuer einen einzelnen Release von der Vorabkontrolle bis zur Nachpruefung.',
    estimatedTime: '8-12 Min',
    intent: 'Release',
    steps: [
      {
        id: 'release-overview',
        title: '1. Overview: Vorabkontrolle',
        tabId: 'overview',
        checklistId: 'overview',
        description: 'Sichere zuerst Workspace, Snapshot und Git-Lage ab.',
        actions: [
          'Pruefe Workspace, Branch und Dirty-Status.',
          'Kontrolliere Top Sets und fehlende Stats.',
        ],
        expectedResults: [
          'Du gehst nicht blind in einen Publish.',
        ],
      },
      {
        id: 'release-flightdeck',
        title: '2. Flight Deck: Publish-Rahmen kontrollieren',
        tabId: 'flightdeck',
        checklistId: 'flightdeck',
        description: 'Stelle sicher, dass Automation, Build und Deploy zu diesem Release passen.',
        actions: [
          'Pruefe Workspace Root, Safe Mode und Automation Toggles.',
          'Kontrolliere Build/Deploy Command.',
        ],
        expectedResults: [
          'Der technische Rahmen fuer den Publish ist richtig gesetzt.',
        ],
      },
      {
        id: 'release-import',
        title: '3. Set Import: Draft und Tracklist fertigstellen',
        tabId: 'import',
        checklistId: 'import',
        description: 'Arbeite Warnungen, Draft und Tracklist vollstaendig ab.',
        actions: [
          'Lade Audio, Cover und Tracklist.',
          'Pruefe alle Kernfelder.',
          'Bereinige die Tracklist.',
        ],
        expectedResults: [
          'Der Draft ist publish-faehig.',
        ],
      },
      {
        id: 'release-publish',
        title: '4. Set Import: Publish und Log lesen',
        tabId: 'import',
        checklistId: 'import',
        description: 'Starte den Publish erst nach Review und lies danach das Log vollstaendig.',
        actions: [
          'Klicke `Publish Set`.',
          'Lies jeden Schritt im Publish Log.',
        ],
        expectedResults: [
          'Du kennst nicht nur das Ergebnis, sondern auch den Ablauf des Publishes.',
        ],
      },
      {
        id: 'release-check',
        title: '5. Overview und Explorer: Nachkontrolle',
        tabId: 'overview',
        checklistId: 'overview',
        description: 'Pruefe das Ergebnis in Folge-Tabs gegen.',
        actions: [
          'Gehe zurueck in Overview und refresh.',
          'Oeffne bei Bedarf `track_stats` im Explorer.',
        ],
        expectedResults: [
          'Das neue Set ist technisch und fachlich bestaetigt.',
        ],
      },
    ],
  },
  adminMaintenance: {
    id: 'adminMaintenance',
    title: 'Szenario: VIP-User und Sessions verwalten',
    description: 'Die gefuehrte Tour fuer administrative Kontrollen an Users, Subscribers und Sessions.',
    estimatedTime: '5-7 Min',
    intent: 'Administration',
    steps: [
      {
        id: 'admin-overview',
        title: '1. Overview: Administrativen Zustand lesen',
        tabId: 'overview',
        checklistId: 'overview',
        description: 'Pruefe zuerst VIP-User- und Session-Zahlen auf Plausibilitaet.',
        actions: [
          'Lies `VIP User` und `Sessions` in den Metrik-Karten.',
          'Pruefe Git- und Runtime-Kontext.',
        ],
        expectedResults: [
          'Du kennst die Ausgangslage der Admin-Daten.',
        ],
      },
      {
        id: 'admin-users',
        title: '2. Explorer: VIP-User verwalten',
        tabId: 'explorer',
        checklistId: 'explorer',
        description: 'Lege User an, loesche alte Konten oder setze Passwoerter zurueck.',
        actions: [
          'Wechsle auf `users`.',
          'Pruefe vorhandene Konten.',
          'Fuehre nur bewusst administrative Aktionen aus.',
        ],
        expectedResults: [
          'VIP-Zugaenge sind sauber gepflegt.',
        ],
      },
      {
        id: 'admin-sessions',
        title: '3. Explorer: Sessions kontrollieren',
        tabId: 'explorer',
        checklistId: 'explorer',
        description: 'Pruefe alte, auffaellige oder unnoetige Sitzungen und widerrufe bei Bedarf gezielt.',
        actions: [
          'Wechsle auf `sessions`.',
          'Lies `created_at`, `expires_at` und Benutzerbezug.',
          'Widerrufe nur gezielt einzelne Sessions.',
        ],
        expectedResults: [
          'Aktive Sitzungen sind nachvollziehbar und sauber.',
        ],
      },
      {
        id: 'admin-subscribers',
        title: '4. Explorer: Subscriber-Pflege optional ergaenzen',
        tabId: 'explorer',
        checklistId: 'explorer',
        description: 'Wenn deine Session- oder User-Pruefung Teil einer groesseren Betriebsrevision ist, nimm Subscriber direkt mit.',
        actions: [
          'Wechsle auf `subscribers`.',
          'Pruefe Statuswerte und Exportbedarf.',
        ],
        expectedResults: [
          'Admin-nahe Bestandsdaten sind mitgeprueft.',
        ],
      },
    ],
  },
  performanceTriage: {
    id: 'performanceTriage',
    title: 'Szenario: Performance- oder Laufzeitproblem eingrenzen',
    description: 'Die gefuehrte Tour fuer langsame Analytics, batchige Imports oder auffaellige lokale Auslastung.',
    estimatedTime: '4-6 Min',
    intent: 'Technische Analyse',
    steps: [
      {
        id: 'perf-overview',
        title: '1. Overview: Kontext sichern',
        tabId: 'overview',
        checklistId: 'overview',
        description: 'Pruefe zuerst, ob du wirklich mit dem erwarteten Workspace und Datenkontext arbeitest.',
        actions: [
          'Kontrolliere Workspace und Branch.',
          'Pruefe, ob aktuelle Aktivitaet im System sichtbar ist.',
        ],
        expectedResults: [
          'Du analysierst nicht das falsche System oder den falschen Branch.',
        ],
      },
      {
        id: 'perf-monitor',
        title: '2. System Monitor: Lasttreiber finden',
        tabId: 'monitor',
        checklistId: 'monitor',
        description: 'Hier trennst du Speicher-, CPU-, Disk- und Prozessursachen voneinander.',
        actions: [
          'Lies RAM, CPU, Disk und Warnungen.',
          'Pruefe Top Prozesse und aktualisiere nach Bedarf erneut.',
        ],
        expectedResults: [
          'Du kennst den wahrscheinlichsten technischen Engpass.',
        ],
      },
      {
        id: 'perf-explorer',
        title: '3. Explorer oder Analytics gezielt gegenpruefen',
        tabId: 'explorer',
        checklistId: 'explorer',
        description: 'Wenn die Last von Datenarbeit zu kommen scheint, grenze die betroffene Tabelle oder Query ein.',
        actions: [
          'Wechsle in Explorer und pruefe nur die relevante Tabelle.',
          'Nutze Read-only SQL fuer kontrollierte Sonderabfragen.',
        ],
        expectedResults: [
          'Du kannst eingrenzen, ob ein konkreter Datenpfad oder Query-Typ auffaellig ist.',
        ],
      },
    ],
  },
};

export const TUTORIAL_TOUR_ORDER = [
  'full',
  'firstSession',
  'databaseAudit',
  'singleRelease',
  'adminMaintenance',
  'performanceTriage',
];

export const TUTORIAL_WORKFLOWS = TUTORIAL_TOUR_ORDER.filter((id) => id !== 'full').map((id) => {
  const tour = TUTORIAL_TOURS[id];
  return {
    id: tour.id,
    title: tour.title,
    description: tour.description,
    steps: tour.steps.map((step) => step.title),
    estimatedTime: tour.estimatedTime,
    intent: tour.intent,
    tabs: Array.from(new Set(tour.steps.map((step) => TAB_LABELS[step.tabId] || step.tabId))),
  };
});

export const TUTORIAL_STEPS = TUTORIAL_TOURS.full.steps;

export const getTutorialSection = (tabId) =>
  TUTORIAL_SECTIONS.find((section) => section.tabId === tabId);

export const getTutorialTour = (tourId) => TUTORIAL_TOURS[tourId];
