#target photoshop

app.bringToFront();
app.displayDialogs = DialogModes.NO;

var sourcePath = "D:/webseeite-main/daumenkino_idee/1765931533777.jpg";
var outputDir = "D:/webseeite-main/docs/agent-system/visual-templates/social/social-auto-output/daumenkino-airdox-letterbeat/photoshop";

var letters = [
  { name: "A", left: 64, top: 318, right: 272, bottom: 688 },
  { name: "I", left: 214, top: 326, right: 398, bottom: 686 },
  { name: "R", left: 342, top: 318, right: 536, bottom: 704 },
  { name: "D", left: 478, top: 308, right: 670, bottom: 712 },
  { name: "O", left: 612, top: 316, right: 812, bottom: 688 },
  { name: "X", left: 754, top: 304, right: 960, bottom: 690 }
];

function ensureFolder(path) {
  var folder = new Folder(path);
  if (!folder.exists) folder.create();
}

function unlockLayer(layer) {
  try {
    if (layer.isBackgroundLayer) layer.isBackgroundLayer = false;
  } catch (e) {}
}

function savePng(doc, targetPath) {
  var outFile = new File(targetPath);
  var options = new ExportOptionsSaveForWeb();
  options.format = SaveDocumentType.PNG;
  options.PNG8 = false;
  options.transparency = true;
  options.interlaced = false;
  options.quality = 100;
  doc.exportDocument(outFile, ExportType.SAVEFORWEB, options);
}

function duplicateCropExport(sourceDoc, item, targetPath) {
  app.activeDocument = sourceDoc;
  sourceDoc.selection.select([
    [item.left, item.top],
    [item.right, item.top],
    [item.right, item.bottom],
    [item.left, item.bottom]
  ]);
  sourceDoc.selection.copy(true);

  var w = item.right - item.left;
  var h = item.bottom - item.top;
  var cropDoc = app.documents.add(w, h, 72, "letter_" + item.name, NewDocumentMode.RGB, DocumentFill.TRANSPARENT);
  cropDoc.paste();
  cropDoc.activeLayer.name = "DAUMENKINO_LETTER_" + item.name;
  savePng(cropDoc, targetPath);
  cropDoc.close(SaveOptions.DONOTSAVECHANGES);
  sourceDoc.selection.deselect();
}

function saveManifest(path) {
  var file = new File(path);
  file.open("w");
  file.encoding = "UTF8";
  file.write("{\n");
  file.write("  \"schema\": \"airdox.daumenkino.photoshop.letter-layers.v1\",\n");
  file.write("  \"source\": \"daumenkino_idee/1765931533777.jpg\",\n");
  file.write("  \"note\": \"Generated by Photoshop JSX. Letter crops are intentionally broad so hand-drawn overlaps remain editable.\",\n");
  file.write("  \"letters\": [\n");
  for (var i = 0; i < letters.length; i += 1) {
    var item = letters[i];
    file.write("    { \"name\": \"" + item.name + "\", \"file\": \"letter-" + item.name + ".png\", \"box\": [" + item.left + ", " + item.top + ", " + item.right + ", " + item.bottom + "] }");
    file.write(i === letters.length - 1 ? "\n" : ",\n");
  }
  file.write("  ]\n");
  file.write("}\n");
  file.close();
}

function main() {
  ensureFolder(outputDir);

  var sourceFile = new File(sourcePath);
  if (!sourceFile.exists) {
    throw new Error("Source not found: " + sourcePath);
  }

  var doc = app.open(sourceFile);
  unlockLayer(doc.layers[0]);

  savePng(doc, outputDir + "/source-base.png");

  for (var i = 0; i < letters.length; i += 1) {
    duplicateCropExport(doc, letters[i], outputDir + "/letter-" + letters[i].name + ".png");
  }

  var psdPath = outputDir + "/daumenkino-letter-workfile.psd";
  var psdFile = new File(psdPath);
  var psdOptions = new PhotoshopSaveOptions();
  psdOptions.layers = true;
  doc.saveAs(psdFile, psdOptions, true, Extension.LOWERCASE);

  saveManifest(outputDir + "/manifest.json");

  doc.close(SaveOptions.DONOTSAVECHANGES);
}

main();
